### ISSUE TITLE
一个比较大型的项目运行在occlum上会运行报错

### ISSUE THREAD

**Issue by gaojunjie03** [occlum/occlum#1023]
我这里有一个flask项目，里面不仅仅只是提供web服务，整个项目里面包含了很多机器学习、数据库读写、pandas、numpy、sklearn等库，我运行这个项目里面其中一个脚本代码，基本上会扫描整个项目，因为里面会有各种import 、from等其他包文件的python代码。  如果此时我在occlum里运行这个项目（即使我不运行flask，只运行里面某个脚本代码）会报错，如：
`(/root/demos/test/python-occlum) root@91754f59ad80:~/demos/test/occlum_instance# occlum run /bin/ee/RunModel.py DataSqlMerge task-b304042a-4905-11ed-80fd-06bfc8dc7b47
Traceback (most recent call last):
  File "/opt/python-occlum/lib/python3.7/pathlib.py", line 375, in gethomedir
    return os.environ['HOME']
  File "/opt/python-occlum/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/ee/RunModel.py", line 3, in <module>
    from apps.service import AlgorithmExecuteService
  File "/bin/ee/apps/__init__.py", line 7, in <module>
    from apps.controller.ServerController import server_mapping
  File "/bin/ee/apps/controller/ServerController.py", line 9, in <module>
    import apps.algorithm
  File "/bin/ee/apps/algorithm/__init__.py", line 5, in <module>
    from apps.algorithm.regression.LinerRegression import LinerRegression
  File "/bin/ee/apps/algorithm/regression/LinerRegression.py", line 12, in <module>
    from matplotlib import pyplot as plt, cm
  File "/opt/python-occlum/lib/python3.7/site-packages/matplotlib/__init__.py", line 890, in <module>
    dict.update(rcParams, _rc_params_in_file(matplotlib_fname()))
  File "/opt/python-occlum/lib/python3.7/site-packages/matplotlib/__init__.py", line 567, in matplotlib_fname
    for fname in gen_candidates():
  File "/opt/python-occlum/lib/python3.7/site-packages/matplotlib/__init__.py", line 564, in gen_candidates
    yield os.path.join(get_configdir(), 'matplotlibrc')
  File "/opt/python-occlum/lib/python3.7/site-packages/matplotlib/__init__.py", line 273, in wrapper
    ret = func(**kwargs)
  File "/opt/python-occlum/lib/python3.7/site-packages/matplotlib/__init__.py", line 510, in get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir)
  File "/opt/python-occlum/lib/python3.7/site-packages/matplotlib/__init__.py", line 469, in _get_config_or_cache_dir
    configdir = Path(xdg_base_getter(), "matplotlib")
  File "/opt/python-occlum/lib/python3.7/site-packages/matplotlib/__init__.py", line 450, in _get_xdg_config_dir
    return os.environ.get('XDG_CONFIG_HOME') or str(Path.home() / ".config")
  File "/opt/python-occlum/lib/python3.7/pathlib.py", line 1088, in home
    return cls(cls()._flavour.gethomedir(None))
  File "/opt/python-occlum/lib/python3.7/pathlib.py", line 378, in gethomedir
    return pwd.getpwuid(os.getuid()).pw_dir
KeyError: 'getpwuid(): uid not found: 0'
`

occlum是否不能运行一些较为复杂的项目呢？

**Comment by qzheng527** [comment]
Generally speaking, Occlum can run very complicated big projects, such as spark, pytorch, tensorflow and many JAVA based applications. But Occlum is not Linux, some mismatch has to be mananged by users. 
For exampke, in your case, there is no "HOME" environment defined, you can add it to Occlum.json (env->default) and rebuild.
Also, there is only one user (id=0) in Occlum libos.

**Comment by gaojunjie03** [comment]
> Generally speaking, Occlum can run very complicated big projects, such as spark, pytorch, tensorflow and many JAVA based applications. But Occlum is not Linux, some mismatch has to be mananged by users. For exampke, in your case, there is no "HOME" environment defined, you can add it to Occlum.json (env->default) and rebuild. Also, there is only one user (id=0) in Occlum libos.
收到 好的 我试试
