### ISSUE TITLE
[BUG]Insufficient resources: mmap failed to allocate 0x200000000 bytes

### ISSUE THREAD

**Issue by thempp66** [occlum/occlum#1062]
# Describe the bug
Some test cases from [Substrate](https://github.com/paritytech/substrate/tree/master/client/executor/wasmtime) work well but doesn't work on occlum environment.

# To reproduce
1. `git clone https://github.com/paritytech/substrate.git`
2. `cd ./substrate/client/executor/wasmtime && occlum-cargo test`
3. Create an occlum instance and copy files from /subject/target/ to /occlum_instance/image/bin
4. Enter occlum instance directory and `occlum run /bin/sc_executor_wasmtime_xxx`

# Expected behavior
Result behave like:
```
running 7 tests
test util::test_is_madvise_working_check_does_not_fail ... ok
test instance_wrapper::decommit_works ... ok
test tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_vanilla ... ok
test tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_cow ... ok
test tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_cow ... ok
test tests::test_max_memory_pages_imported_memory_without_precompilation_legacy_instance_reuse ... ok
test tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_vanilla ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```
# Logs
test cases failed:
```
running 41 tests
test tests::test_instances_without_reuse_are_not_leaked ... ignored
test tests::test_consume_over_1mb_of_stack_does_trap_pooling_cow ... FAILED
test tests::test_consume_under_1mb_of_stack_does_not_trap_pooling_vanilla ... FAILED
test tests::test_consume_under_1mb_of_stack_does_not_trap_pooling_cow ... FAILED
test tests::test_consume_over_1mb_of_stack_does_trap_pooling_vanilla ... FAILED
test instance_wrapper::decommit_works ... FAILED
test tests::test_max_memory_pages_exported_memory_with_precompilation_pooling_cow ... FAILED
test tests::test_max_memory_pages_exported_memory_without_precompilation_legacy_instance_reuse ... FAILED
test tests::test_max_memory_pages_exported_memory_with_precompilation_pooling_vanilla ... FAILED
test tests::test_consume_over_1mb_of_stack_does_trap_recreate_instance_cow ... FAILED
test tests::test_consume_under_1mb_of_stack_does_not_trap_legacy_instance_reuse ... FAILED
test tests::test_consume_under_1mb_of_stack_does_not_trap_recreate_instance_cow ... FAILED
test tests::test_consume_over_1mb_of_stack_does_trap_legacy_instance_reuse ... FAILED
test tests::test_consume_under_1mb_of_stack_does_not_trap_recreate_instance_vanilla ... FAILED
test tests::test_consume_over_1mb_of_stack_does_trap_recreate_instance_vanilla ... FAILED
test tests::test_max_memory_pages_exported_memory_with_precompilation_recreate_instance_vanilla ... FAILED
test tests::test_max_memory_pages_exported_memory_with_precompilation_recreate_instance_cow ... FAILED
test tests::test_max_memory_pages_exported_memory_without_precompilation_pooling_vanilla ... FAILED
test tests::test_max_memory_pages_exported_memory_without_precompilation_pooling_cow ... FAILED
test tests::test_max_memory_pages_imported_memory_with_precompilation_pooling_cow ... FAILED
test tests::test_max_memory_pages_exported_memory_without_precompilation_recreate_instance_cow ... FAILED
test tests::test_max_memory_pages_imported_memory_with_precompilation_pooling_vanilla ... FAILED
test tests::test_max_memory_pages_exported_memory_without_precompilation_recreate_instance_vanilla ... FAILED
test tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_cow ... FAILED
test tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_vanilla ... FAILED
test tests::test_max_memory_pages_imported_memory_without_precompilation_legacy_instance_reuse ... FAILED
test tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_cow ... FAILED
test tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_vanilla ... FAILED
test tests::test_max_memory_pages_imported_memory_with_precompilation_recreate_instance_cow ... FAILED
test tests::test_max_memory_pages_imported_memory_with_precompilation_recreate_instance_vanilla ... FAILED
test util::test_is_madvise_working_check_does_not_fail ... FAILED
test tests::test_nan_canonicalization_pooling_cow ... FAILED
test tests::test_nan_canonicalization_pooling_vanilla ... FAILED
test tests::test_stack_depth_reaching_pooling_vanilla ... FAILED
test tests::test_stack_depth_reaching_pooling_cow ... FAILED
test tests::test_stack_depth_reaching_recreate_instance_cow ... FAILED
test tests::test_stack_depth_reaching_recreate_instance_vanilla ... FAILED
test tests::test_stack_depth_reaching_legacy_instance_reuse ... FAILED
test tests::test_nan_canonicalization_legacy_instance_reuse ... FAILED
test tests::test_nan_canonicalization_recreate_instance_cow ... FAILED
test tests::test_nan_canonicalization_recreate_instance_vanilla ... FAILED

failures:

---- tests::test_consume_over_1mb_of_stack_does_trap_pooling_cow stdout ----
thread 'tests::test_consume_over_1mb_of_stack_does_trap_pooling_cow' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::test_consume_under_1mb_of_stack_does_not_trap_pooling_vanilla stdout ----
thread 'tests::test_consume_under_1mb_of_stack_does_not_trap_pooling_vanilla' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_consume_under_1mb_of_stack_does_not_trap_pooling_cow stdout ----
thread 'tests::test_consume_under_1mb_of_stack_does_not_trap_pooling_cow' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_consume_over_1mb_of_stack_does_trap_pooling_vanilla stdout ----
thread 'tests::test_consume_over_1mb_of_stack_does_trap_pooling_vanilla' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- instance_wrapper::decommit_works stdout ----
thread 'instance_wrapper::decommit_works' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/instance_wrapper.rs:417:74

---- tests::test_max_memory_pages_exported_memory_with_precompilation_pooling_cow stdout ----
thread 'tests::test_max_memory_pages_exported_memory_with_precompilation_pooling_cow' panicked at 'called `Result::unwrap()` on an `Err` value: Other("cannot create the engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:167:85

---- tests::test_max_memory_pages_exported_memory_without_precompilation_legacy_instance_reuse stdout ----
thread 'tests::test_max_memory_pages_exported_memory_without_precompilation_legacy_instance_reuse' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_exported_memory_with_precompilation_pooling_vanilla stdout ----
thread 'tests::test_max_memory_pages_exported_memory_with_precompilation_pooling_vanilla' panicked at 'called `Result::unwrap()` on an `Err` value: Other("cannot create the engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:167:85

---- tests::test_consume_over_1mb_of_stack_does_trap_recreate_instance_cow stdout ----
thread 'tests::test_consume_over_1mb_of_stack_does_trap_recreate_instance_cow' panicked at 'unexpected error: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:252:18

---- tests::test_consume_under_1mb_of_stack_does_not_trap_legacy_instance_reuse stdout ----
thread 'tests::test_consume_under_1mb_of_stack_does_not_trap_legacy_instance_reuse' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:238:39

---- tests::test_consume_under_1mb_of_stack_does_not_trap_recreate_instance_cow stdout ----
thread 'tests::test_consume_under_1mb_of_stack_does_not_trap_recreate_instance_cow' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:238:39

---- tests::test_consume_over_1mb_of_stack_does_trap_legacy_instance_reuse stdout ----
thread 'tests::test_consume_over_1mb_of_stack_does_trap_legacy_instance_reuse' panicked at 'unexpected error: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:252:18

---- tests::test_consume_under_1mb_of_stack_does_not_trap_recreate_instance_vanilla stdout ----
thread 'tests::test_consume_under_1mb_of_stack_does_not_trap_recreate_instance_vanilla' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:238:39

---- tests::test_consume_over_1mb_of_stack_does_trap_recreate_instance_vanilla stdout ----
thread 'tests::test_consume_over_1mb_of_stack_does_trap_recreate_instance_vanilla' panicked at 'unexpected error: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:252:18

---- tests::test_max_memory_pages_exported_memory_with_precompilation_recreate_instance_vanilla stdout ----
thread 'tests::test_max_memory_pages_exported_memory_with_precompilation_recreate_instance_vanilla' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_exported_memory_with_precompilation_recreate_instance_cow stdout ----
thread 'tests::test_max_memory_pages_exported_memory_with_precompilation_recreate_instance_cow' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_exported_memory_without_precompilation_pooling_vanilla stdout ----
thread 'tests::test_max_memory_pages_exported_memory_without_precompilation_pooling_vanilla' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_max_memory_pages_exported_memory_without_precompilation_pooling_cow stdout ----
thread 'tests::test_max_memory_pages_exported_memory_without_precompilation_pooling_cow' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_max_memory_pages_imported_memory_with_precompilation_pooling_cow stdout ----
thread 'tests::test_max_memory_pages_imported_memory_with_precompilation_pooling_cow' panicked at 'called `Result::unwrap()` on an `Err` value: Other("cannot create the engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:167:85

---- tests::test_max_memory_pages_exported_memory_without_precompilation_recreate_instance_cow stdout ----
thread 'tests::test_max_memory_pages_exported_memory_without_precompilation_recreate_instance_cow' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_imported_memory_with_precompilation_pooling_vanilla stdout ----
thread 'tests::test_max_memory_pages_imported_memory_with_precompilation_pooling_vanilla' panicked at 'called `Result::unwrap()` on an `Err` value: Other("cannot create the engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:167:85

---- tests::test_max_memory_pages_exported_memory_without_precompilation_recreate_instance_vanilla stdout ----
thread 'tests::test_max_memory_pages_exported_memory_without_precompilation_recreate_instance_vanilla' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_cow stdout ----
thread 'tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_cow' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_vanilla stdout ----
thread 'tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_vanilla' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_max_memory_pages_imported_memory_without_precompilation_legacy_instance_reuse stdout ----
thread 'tests::test_max_memory_pages_imported_memory_without_precompilation_legacy_instance_reuse' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_cow stdout ----
thread 'tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_cow' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_vanilla stdout ----
thread 'tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_vanilla' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_imported_memory_with_precompilation_recreate_instance_cow stdout ----
thread 'tests::test_max_memory_pages_imported_memory_with_precompilation_recreate_instance_cow' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- tests::test_max_memory_pages_imported_memory_with_precompilation_recreate_instance_vanilla stdout ----
thread 'tests::test_max_memory_pages_imported_memory_with_precompilation_recreate_instance_vanilla' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:409:6

---- util::test_is_madvise_working_check_does_not_fail stdout ----
thread 'util::test_is_madvise_working_check_does_not_fail' panicked at 'assertion failed: is_madvise_working().is_ok()', client/executor/wasmtime/src/util.rs:148:5

---- tests::test_nan_canonicalization_pooling_cow stdout ----
thread 'tests::test_nan_canonicalization_pooling_cow' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_nan_canonicalization_pooling_vanilla stdout ----
thread 'tests::test_nan_canonicalization_pooling_vanilla' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_stack_depth_reaching_pooling_vanilla stdout ----
thread 'tests::test_stack_depth_reaching_pooling_vanilla' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_stack_depth_reaching_pooling_cow stdout ----
thread 'tests::test_stack_depth_reaching_pooling_cow' panicked at 'cannot create runtime: Other("cannot create the wasmtime engine: failed to create memory pool mapping: mmap failed to allocate 0x3080000000 bytes: Out of memory (os error 12)")', client/executor/wasmtime/src/tests.rs:173:10

---- tests::test_stack_depth_reaching_recreate_instance_cow stdout ----
thread 'tests::test_stack_depth_reaching_recreate_instance_cow' panicked at 'unexpected error: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:310:18

---- tests::test_stack_depth_reaching_recreate_instance_vanilla stdout ----
thread 'tests::test_stack_depth_reaching_recreate_instance_vanilla' panicked at 'unexpected error: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:310:18

---- tests::test_stack_depth_reaching_legacy_instance_reuse stdout ----
thread 'tests::test_stack_depth_reaching_legacy_instance_reuse' panicked at 'unexpected error: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:310:18

---- tests::test_nan_canonicalization_legacy_instance_reuse stdout ----
thread 'tests::test_nan_canonicalization_legacy_instance_reuse' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:288:74

---- tests::test_nan_canonicalization_recreate_instance_cow stdout ----
thread 'tests::test_nan_canonicalization_recreate_instance_cow' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:288:74

---- tests::test_nan_canonicalization_recreate_instance_vanilla stdout ----
thread 'tests::test_nan_canonicalization_recreate_instance_vanilla' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeConstruction(Other("failed to instantiate a new WASM module instance: Insufficient resources: mmap failed to allocate 0x200000000 bytes"))', client/executor/wasmtime/src/tests.rs:288:74


failures:
    instance_wrapper::decommit_works
    tests::test_consume_over_1mb_of_stack_does_trap_legacy_instance_reuse
    tests::test_consume_over_1mb_of_stack_does_trap_pooling_cow
    tests::test_consume_over_1mb_of_stack_does_trap_pooling_vanilla
    tests::test_consume_over_1mb_of_stack_does_trap_recreate_instance_cow
    tests::test_consume_over_1mb_of_stack_does_trap_recreate_instance_vanilla
    tests::test_consume_under_1mb_of_stack_does_not_trap_legacy_instance_reuse
    tests::test_consume_under_1mb_of_stack_does_not_trap_pooling_cow
    tests::test_consume_under_1mb_of_stack_does_not_trap_pooling_vanilla
    tests::test_consume_under_1mb_of_stack_does_not_trap_recreate_instance_cow
    tests::test_consume_under_1mb_of_stack_does_not_trap_recreate_instance_vanilla
    tests::test_max_memory_pages_exported_memory_with_precompilation_pooling_cow
    tests::test_max_memory_pages_exported_memory_with_precompilation_pooling_vanilla
    tests::test_max_memory_pages_exported_memory_with_precompilation_recreate_instance_cow
    tests::test_max_memory_pages_exported_memory_with_precompilation_recreate_instance_vanilla
    tests::test_max_memory_pages_exported_memory_without_precompilation_legacy_instance_reuse
    tests::test_max_memory_pages_exported_memory_without_precompilation_pooling_cow
    tests::test_max_memory_pages_exported_memory_without_precompilation_pooling_vanilla
    tests::test_max_memory_pages_exported_memory_without_precompilation_recreate_instance_cow
    tests::test_max_memory_pages_exported_memory_without_precompilation_recreate_instance_vanilla
    tests::test_max_memory_pages_imported_memory_with_precompilation_pooling_cow
    tests::test_max_memory_pages_imported_memory_with_precompilation_pooling_vanilla
    tests::test_max_memory_pages_imported_memory_with_precompilation_recreate_instance_cow
    tests::test_max_memory_pages_imported_memory_with_precompilation_recreate_instance_vanilla
    tests::test_max_memory_pages_imported_memory_without_precompilation_legacy_instance_reuse
    tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_cow
    tests::test_max_memory_pages_imported_memory_without_precompilation_pooling_vanilla
    tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_cow
    tests::test_max_memory_pages_imported_memory_without_precompilation_recreate_instance_vanilla
    tests::test_nan_canonicalization_legacy_instance_reuse
    tests::test_nan_canonicalization_pooling_cow
    tests::test_nan_canonicalization_pooling_vanilla
    tests::test_nan_canonicalization_recreate_instance_cow
    tests::test_nan_canonicalization_recreate_instance_vanilla
    tests::test_stack_depth_reaching_legacy_instance_reuse
    tests::test_stack_depth_reaching_pooling_cow
    tests::test_stack_depth_reaching_pooling_vanilla
    tests::test_stack_depth_reaching_recreate_instance_cow
    tests::test_stack_depth_reaching_recreate_instance_vanilla
    util::test_is_madvise_working_check_does_not_fail

test result: FAILED. 0 passed; 40 failed; 1 ignored; 0 measured; 0 filtered out; finished in 1.29s
```

# Environment

- HW: SGX1, SGX2
- OS: Ubuntu20.04
- Occlum version: [e.g. 0.28.0]

# Additional context
I tried different size of memory of `Occlum.json` but it still doesn't work. Below is my `Occlum.json`. 
```
{
    "resource_limits": {
        "kernel_space_heap_size": "9000MB",
        "kernel_space_stack_size": "1MB",
        "user_space_size": "4096MB",
        "max_num_of_threads": 1024
    },
    "process": {
        "default_stack_size": "4MB",
        "default_heap_size": "32MB",
        "default_mmap_size": "100MB"
    },

    "entry_points": [
        "/bin"
    ],
    "env": {
        "default": [
            "OCCLUM=yes"
        ],
        "untrusted": [
            "EXAMPLE"
        ]
    },
    "metadata": {
        "product_id": 0,
        "version_number": 0,
        "debuggable": true,
        "enable_kss": false,
        "family_id": {
            "high": "0x0",
            "low": "0x0"
        },
        "ext_prod_id": {
            "high": "0x0",
            "low": "0x0"
        },
        "pkru": 0
    },
    "mount": [
        {
            "target": "/",
            "type": "unionfs",
            "options": {
                "layers": [
                    {
                        "target": "/",
                        "type": "sefs",
                        "source": "./build/mount/__ROOT",
                        "options": {
                            "MAC": ""
                        }
                    },
                    {
                        "target": "/",
                        "type": "sefs",
                        "source": "./run/mount/__ROOT"
                    }
                ]
            }
        },
        {
            "target": "/host",
            "type": "hostfs",
            "source": "."
        },
        {
            "target": "/proc",
            "type": "procfs"
        },
        {
            "target": "/dev",
            "type": "devfs"
        }
    ]
}

```

# Possible solution/Implementation

I guess the cause of this problem may be the limit of occlum operating system or SGX enclave. There is a similar issue from substrate. https://github.com/paritytech/substrate/issues/12538 . It seems to be limited by the OS. If so, how could we make it work?

Looking forward to your reply, thanks!

**Comment by volcano0dr** [comment]
You can try to enlarge the `resource_limits.user_space_size` in Occlum.json.
refer to [resource_config_guide](https://github.com/occlum/occlum/blob/master/docs/resource_config_guide.md)

**Comment by thempp66** [comment]
> 

I tryied to enlarge resource_limits.user_space_size to 16GB, some test cases still failed. The Error shows it require 0x200000000 bytes (8GB) which does't reach the user_space_size (16GB) I set.

**Comment by jessehui** [comment]
> Does Occlum support virtual memory?

Occlum can only manage virtual memory. 



> > 
> 
> I tryied to enlarge resource_limits.user_space_size to 16GB, some test cases still failed. The Error shows it require 0x200000000 bytes (8GB) which does't reach the user_space_size (16GB) I set.

I am not familiar with your application. If a test case ends but not returning memory, the latter test cases can fail due to insufficient memory.

@thempp66

**Comment by thempp66** [comment]
> > Does Occlum support virtual memory?
> 
> Occlum can only manage virtual memory.
> 
> > > 
> > 
> > 
> > I tryied to enlarge resource_limits.user_space_size to 16GB, some test cases still failed. The Error shows it require 0x200000000 bytes (8GB) which does't reach the user_space_size (16GB) I set.
> 
> I am not familiar with your application. If a test case ends but not returning memory, the latter test cases can fail due to insufficient memory.
> 
> @thempp66

Thanks for your reply.
Actually, the same code works well in Linux. That is what I confuse.
