### ISSUE TITLE
Perform DCAP remote attestation on hello_world project

### ISSUE THREAD

**Issue by graziadonghia** [occlum/occlum#1124]
Hello, I'm studying how DCAP remote attestation works on Occlum. I already tried both the [dcap test](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/dcap) and the [init_ra_flow test](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/init_ra_flow) but there are still several aspects that I cannot figure out:

1. How can I apply the `dcap_c_test` to a general program running with Occlum such as the [hello worls](https://github.com/occlum/occlum/tree/master/demos/hello_c) project? I mean, is it possible to eventually modify the code of `dcap_c_test` so that it can take the code inside the hello occlum instance and perform remote attestation on it? As far as I understood, when I run the `dcap_c_test` it automatically generates an enclave and puts the code inside an occlum instance. Hence, how can I do the same thing but with an ar
arbitrary program?

2. Does the `init_ra_flow` test perform remote attestation of a python project by using the GRPC server as verifier? I don't know, maybe I didn't properly understand how this demo works

I hope I've been clear in explaining my problems, thank you

**Comment by qzheng527** [comment]
@graziadonghia 
1. dcap_c_test is a simple demo program. To embed the DCAP function in your program such as hello_world, you can call the [DCAP APIs](https://github.com/occlum/occlum/blob/master/tools/toolchains/dcap_lib/inc/occlum_dcap.h) and link the library into your program. For that, you could refer to the dcap_c_test demo. 
2. init_ra_flow shows how to use the [GRPC-RATLS libraies ](https://github.com/occlum/occlum/tree/master/demos/ra_tls) to implment a simple flask demo + KMS in TEE. The purpose of this demo is to seperate the RA flow with the real application. So generally the python application doesn't need to participate the RA flow. All the RA/KMS works are done in Occlum init process.

**Comment by graziadonghia** [comment]
ok, actually I managed the separation between the quote generation and the quote verification in two different occlum instances. However, is it possible to run the quote verification outside an enclave? unfortunately I receive this error: `thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "IOCTRL IOCTL_VER_DCAP_QUOTE failed"', src/lib.rs:84:40` even if the quote value and all related stuff is correct, in fact it works only if I run the quote verification inside an enclave.

**Comment by qzheng527** [comment]
> ok, actually I managed the separation between the quote generation and the quote verification in two different occlum instances. However, is it possible to run the quote verification outside an enclave? unfortunately I receive this error: `thread '<unnamed>' panicked at 'called `Result::unwrap()`on an`Err` value: "IOCTRL IOCTL_VER_DCAP_QUOTE failed"', src/lib.rs:84:40` even if the quote value and all related stuff is correct, in fact it works only if I run the quote verification inside an enclave (i.e an occlum instance).

If you want to do quote verification outside Occlum enclave, you can't use the DCAP libs Occlum provided. You can just try [Intel sample code](https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/DCAP_1.14/SampleCode/QuoteVerificationSample) for quote verification.

**Comment by fearlessfe** [comment]
@qzheng527 In the intel sample code, the QuoteGenerationSample will generate a `quote.dat` file, the QuoteVerificationSample can verify the quote file. But in the `init_ra_flow`， there is no `quote.dat` file generated.
