### ISSUE TITLE
[BUG]symbol not found

### ISSUE THREAD

**Issue by lijun0314** [occlum/occlum#1139]
# Describe the bug
java-11-openjdk is missing `libfreetype.so.6`, so I installed `libfreetype.so.6` in the container with the command `apt-get install libfreetype6`. Then I copied this library into occlum. When the program runs again the following error occurs.
```
2023-02-06 08:50:44.933 ERROR 2 --- [nio-9093-exec-1] c.y.i.handler.DKExceptionHandler         : org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-openjdk/jre/lib/libfontmanager.so: Error relocating /opt/occlum/glibc/lib/libfreetype.so.6: __memcpy_chk: symbol not found
```
# To reproduce
Sorry, this is not a simple demo, it is difficult to reproduce after adding items.

# Expected behavior
libfreetype.so.6 does not report an error.

# Logs
```
2023-02-06 08:50:44.933 ERROR 2 --- [nio-9093-exec-1] c.y.i.handler.DKExceptionHandler         : org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-openjdk/jre/lib/libfontmanager.so: Error relocating /opt/occlum/glibc/lib/libfreetype.so.6: __memcpy_chk: symbol not found
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at cn.ysys.security.filter.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at cn.ysys.filter.SessionFilter.doFilter(SessionFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:152)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at cn.ysys.security.filter.EncryptFilter.doFilter(EncryptFilter.java:68)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:141)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:97)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.csp.sentinel.adapter.servlet.CommonFilter.doFilter(CommonFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

# Environment

- HW: [SGX2] 
- OS: [Ubuntu20.04]
- Occlum version: [0.29.4]

# Possible solution/Implementation
This is the information of `libfreetype.so.6`
```
root@9c83004904db:~/demos/java/testDCAP# ldd libfreetype.so.6
	linux-vdso.so.1 (0x00007ffc678be000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f113254d000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1132531000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f113233f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f11321f0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f113264d000)
```
I found that there is `__memcpy_chk` in `libc.so.6`, but I don't know why the `symbol not found`error still occurs.
```
root@9c83004904db:~/demos/java/occlum_instance/image/opt/occlum/glibc/lib# nm -D libc.so.6 | grep "mem"
000000000008e240 T __libc_memalign
00000000001c1b60 V __memalign_hook
0000000000112630 i __memcpy_chk
00000000001126f0 i __memmove_chk
0000000000092660 i __mempcpy
00000000001127b0 i __mempcpy_chk
0000000000097de0 T __mempcpy_small
0000000000112870 i __memset_chk
0000000000093bd0 i __rawmemchr
000000000013b990 T __sigismember
0000000000113a00 T __wmemcpy_chk
0000000000113a30 T __wmemmove_chk
0000000000113a60 T __wmempcpy_chk
0000000000113c80 i __wmemset_chk
0000000000090a40 T _obstack_memory_used
0000000000081bf0 T fmemopen
00000000000817e0 T fmemopen
00000000000d0ad0 W group_member
000000000008e240 W memalign
0000000000092970 W memccpy
```
This is the yaml file content:
```
includes:
  - base.yaml
  - java-11-openjdk.yaml

targets:
  # copy the web server
  - target: /usr/lib/spring
    copy:
      - files:
        - ../gs-messaging-stomp-websocket/complete/target/gs-messaging-stomp-websocket-0.1.0.jar
  # copy the web server
  - target: /usr/lib/spring/config
    copy:
      - files:
        - ../gs-messaging-stomp-websocket/complete/target/config/application.properties

  # copy lib
  - target: /opt/occlum/glibc/lib
    copy:
      - files:
        - ../testDCAP/libc.so.6
        - ../testDCAP/libpng16.so.16
        - ../testDCAP/libfreetype.so.6
        - ../testDCAP/libfreetype.so.6.17.1
 
    createlinks:
      - src: libfreetype.so.6
        linkname: libfreetype.so.6.17.1

  # copy clib
  - target: /usr/lib
    copy:
      - files:
        - /opt/occlum/toolchains/dcap_lib/musl/libocclum_dcap.so.0.1.0
        - ../testDCAP/libtestDCAP.so
        - ../testDCAP/libgcc_s.so.1
        - ../testDCAP/libm.so.6
```
Here is env.default:
```
env.default = [ "LD_LIBRARY_PATH=/usr/lib/jvm/java-11-openjdk/jre/lib/server:/usr/lib/jvm/java-11-openjdk/jre/lib:/usr/lib/jvm/java-11-openjdk/jre/../lib:/lib:/opt/occlum/glibc/lib" ]
```
and 
```
root@9c83004904db:~/demos/java/occlum_instance/image/opt/occlum/glibc/lib# ls
ld-linux-x86-64.so.2  libfreetype.so.6       libm.so.6       libz.so.1
libc.so.6             libfreetype.so.6.17.1  libpng16.so.16
```
Do you have any suggestions for this issue?
Also, I would like to ask when a project needs third-party libraries, how to set up the runtime environment needed for the project through yaml file, env.default variable?

**Comment by guzongmin** [comment]
It seems that your JVM is compiled with musl and the libfreetype.so.6 is linked with glibc. Please check both of them to make sure they are correctly linked. 
A better solution is to create the occlum instance with bom tool, which would check the dependency.
