### ISSUE TITLE
[BUG]ImportError: libdeflate.so.0: failed to map segment from shared object

### ISSUE THREAD

**Issue by bai18331272258** [occlum/occlum#1214]
# Describe the bug
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from torchvision import models
  File "/opt/python-occlum/lib/python3.8/site-packages/torchvision/__init__.py", line 6, in <mo
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/opt/python-occlum/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/opt/python-occlum/lib/python3.8/site-packages/torchvision/datasets/_optical_flow.py", odule>
    from PIL import Image
  File "/opt/python-occlum/lib/python3.8/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: libdeflate.so.0: failed to map segment from shared object
memory allocation of 32768 bytes failed
/opt/occlum/build/bin/occlum: line 340:  9980 Illegal instruction     (core dumped) RUST_BACKTRce_dir/build/bin/occlum-run" "$@"

# To reproduce
1. docker pull occlum/occlum:0.29.3-ubuntu20.04
2. bash ./install_python_with_conda.sh
3. Changed the content of demo.py
4. bash ./run_pytorch_on_occlum.sh

# Expected behavior

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW:SGX2
- OS: Ubuntu18.04
- Occlum version:0.29.3

# Additional context
The above error occurs when running bash./run_pytorch_on_occlum.sh after I changed the contents of demo.py.   So  I need your help.

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by qzheng527** [comment]
@bai18331272258 **memory allocation of 32768 bytes failed**, that means `resource_limits.kernel_space_heap_size` has to be enlarged. Please refer to [resource_config_guide](https://github.com/occlum/occlum/blob/master/docs/resource_config_guide.md) for details.
