### ISSUE TITLE
[BUG] Python platform.system() Unsupported operating system: Occlum

### ISSUE THREAD

**Issue by rodrigo-pedro** [occlum/occlum#1256]
# Describe the bug
The Ultralytics python library calls platform.system(). When called inside Occlum, this function returns "Occlum", which causes Ultralytics to throw the following error:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from ultralytics import YOLO
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 36, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 17, in <module>
    from ultralytics.yolo.utils import LINUX, LOGGER, ROOT, yaml_load
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/yolo/utils/__init__.py", line 487, in <module>
    USER_CONFIG_DIR = os.getenv('YOLO_CONFIG_DIR', get_user_config_dir())  # Ultralytics settings dir
  File "/opt/python-occlum/lib/python3.8/site-packages/ultralytics/yolo/utils/__init__.py", line 475, in get_user_config_dir
    raise ValueError(f'Unsupported operating system: {platform.system()}')
ValueError: Unsupported operating system: Occlum

# To reproduce
1. Execute a python script that imports Ultralytics inside Occlum

Alternatively, simple run a python script that calls platform.system(). It should return "Occlum".

# Expected behavior
platform.system() should return "Linux" so the Ultralytics library doesn't throw an error.

# Environment

- HW: SGX2
- OS: Ubuntu20.04 (occlum/occlum:0.29.5-ubuntu20.04)
- Occlum version: 0.29.5

**Comment by qzheng527** [comment]
@rodrigo-pedro Thanks for throwing this. It is a known "issue" for a while. 
Argument continues for some time on either return "Linux" to make application/libraries happy/compatible or return "Occlum" to indicate what OS exactly it is. 
Occlum team will make a decision soon.

**Comment by rodrigo-pedro** [comment]
@qzheng527  Could you please advise me on the necessary modifications to the Occlum code for it to function properly with my application? Just as a temporary workaround.

I would say the best option would be to add some optional flag when compiling (eg OS_LINUX). Seems like a good compromise.

**Comment by qzheng527** [comment]
@rodrigo-pedro You can try the [temp patch](https://github.com/qzheng527/occlum/commit/cf0a1bbcac81b5a56c628167f9f6d68754956188).
But it is not guranteed that this patch would be merged exactly same in future.
