### ISSUE TITLE
[BUG]IOCTRL IOCTL_VER_DCAP_QUOTE failed

### ISSUE THREAD

**Issue by prz23** [occlum/occlum#1520]
I am using the remote attestation feature of DCAP and called the verify_quote function, but then encountered an error with the ioctl operation failing.

occlum/occlum:0.29.7-ubuntu20.04

```
    pub fn verify_quote(
        &mut self,
        verify_arg: *mut IoctlVerDCAPQuoteArg,
    ) -> Result<i32, &'static str> {
        let ret = unsafe { libc::ioctl(self.fd, IOCTL_VER_DCAP_QUOTE, verify_arg) };
        if ret < 0 {
            println!("ret = {}", ret);
            Err("IOCTRL IOCTL_VER_DCAP_QUOTE failed")
        } else {
            Ok(0)
        }
    }
```
```
Generate quote with report data : [226, 202, 119, 211, 193, 113, 228, 158, 210, 184, 96, 75, 27, 163, 223, 8, 85, 232, 218, 238, 107, 252, 177, 225, 53, 217, 131, 202, 70, 186, 110, 64, 12, 221, 240, 21, 128, 170, 199, 181, 227, 124, 60, 28, 16, 32, 60, 123, 7, 72, 160, 105, 228, 48, 205, 67, 11, 159, 14, 30, 155, 235, 229, 166]
DCAP generate quote successfully
Report data from Quote: '[226, 202, 119, 211, 193, 113, 228, 158, 210, 184, 96, 75, 27, 163, 223, 8, 85, 232, 218, 238, 107, 252, 177, 225, 53, 217, 131, 202, 70, 186, 110, 64, 12, 221, 240, 21, 128, 170, 199, 181, 227, 124, 60, 28, 16, 32, 60, 123, 7, 72, 160, 105, 228, 48, 205, 67, 11, 159, 14, 30, 155, 235, 229, 166]' exactly matches.

SGX ISV Family ID:
         Low 8 bytes: 0x0000000000000000
         high 8 bytes: 0x0000000000000000

SGX ISV EXT Product ID:
         Low 8 bytes: 0x0000000000000000
         high 8 bytes: 0x0000000000000000

SGX CONFIG ID:
        [00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
        [00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
        [00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
        [00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]

SGX CONFIG SVN:  0000
ret = -1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "IOCTRL IOCTL_VER_DCAP_QUOTE failed"', /root/occlum-ra/occlum-ra/src/occlum_dcap.rs:84:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

OCCLUM_LOG_LEVEL=debug：
```
[2024-03-28T06:08:18.227Z][DEBUG][T2][#93][···Write] write: fd: 1
SGX CONFIG SVN:  0000
[2024-03-28T06:08:18.227Z][DEBUG][T2][#94][···Ioctl] ioctl: fd: 3, cmd: NonBuiltin(NonBuiltinIoctlCmd { cmd_num: StructuredIoctlNum { cmd_id: 10, magic_char: 115, arg_size: 48, arg_type: InputOutput }, arg_buf: Some([0, 0, 194, 130, 250, 126, 0, 0, 125, 18, 0, 0, 250, 126, 0, 0, 92, 235, 95, 130, 250, 126, 0, 0, 88, 235, 95, 130, 250, 126, 0, 0, 176, 0, 0, 0, 250, 126, 0, 0, 192, 240, 192, 130, 250, 126, 0, 0]) })
[2024-03-28T06:08:18.438Z][ERROR][T2][#94][···Ioctl] EINVAL (#22, Invalid argument): occlum_ocall_sgx_ver_dcap_quote failed [line = 105, file = src/util/sgx/dcap/quote_verifier.rs]
[2024-03-28T06:08:18.438Z][ERROR][T2][#94][···Ioctl] Error = EINVAL (#22, Invalid argument): IOCTLError
[2024-03-28T06:08:18.438Z][DEBUG][T2][#95][···Write] write: fd: 1
```

The DCAP demo also has similar errors. Through the debug logs, it can be seen that the ioctl call to occlum_ocall_sgx_ver_dcap_quote has failed.
```
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <StackMinSize>1048576</StackMinSize>
    <HeapInitSize>33554432</HeapInitSize>
    <HeapMaxSize>1073741824</HeapMaxSize>
    <HeapMinSize>33554432</HeapMinSize>
    <TCSNum>32</TCSNum>
    <TCSMaxNum>4096</TCSMaxNum>
    <TCSMinPool>32</TCSMinPool>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>1</MiscSelect>
    <MiscMask>0x0</MiscMask>
    <ReservedMemMaxSize>314572800</ReservedMemMaxSize>
    <ReservedMemMinSize>314572800</ReservedMemMinSize>
    <ReservedMemInitSize>314572800</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
    <EnableKSS>0</EnableKSS>
    <ISVEXTPRODID_H>0</ISVEXTPRODID_H>
    <ISVEXTPRODID_L>0</ISVEXTPRODID_L>
    <ISVFAMILYID_H>0</ISVFAMILYID_H>
    <ISVFAMILYID_L>0</ISVFAMILYID_L>
    <PKRU>0</PKRU>
</EnclaveConfiguration>
tcs_num 32, tcs_max_num 4096, tcs_min_pool 32
The required memory is 386625536B.
The required memory is 0x170b7000, 377564 KB.
Succeed.
Built the Occlum image and enclave successfully
occlum run rust test /bin/dcap_test
Generate quote with report data : Dcap demo sample
DCAP generate quote successfully
Report data from Quote: 'Dcap demo sample' exactly matches.

SGX ISV Family ID:
         Low 8 bytes: 0x0000000000000000
         high 8 bytes: 0x0000000000000000

SGX ISV EXT Product ID:
         Low 8 bytes: 0x0000000000000000
         high 8 bytes: 0x0000000000000000

SGX CONFIG ID:
        [00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
        [00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
        [00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
        [00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]

SGX CONFIG SVN:  0000
OS error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', examples/dcap_test.rs:90:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@user:~/demos/remote_attestation/dcap#
```
OCCLUM_LOG_LEVEL=debug：
```
SGX CONFIG SVN:  0000
[2024-03-28T06:18:11.010Z][DEBUG][T2][#170][···Ioctl] ioctl: fd: 3, cmd: NonBuiltin(NonBuiltinIoctlCmd { cmd_num: StructuredIoctlNum { cmd_id: 10, magic_char: 115, arg_size: 48, arg_type: InputOutput }, arg_buf: Some([224, 197, 92, 117, 153, 127, 0, 0, 125, 18, 0, 0, 0, 0, 0, 0, 232, 186, 156, 119, 153, 127, 0, 0, 248, 186, 156, 119, 153, 127, 0, 0, 176, 0, 0, 0, 153, 127, 0, 0, 112, 216, 92, 117, 153, 127, 0, 0]) })
[2024-03-28T06:18:11.214Z][ERROR][T2][#170][···Ioctl] EINVAL (#22, Invalid argument): occlum_ocall_sgx_ver_dcap_quote failed [line = 105, file = src/util/sgx/dcap/quote_verifier.rs]
[2024-03-28T06:18:11.214Z][ERROR][T2][#170][···Ioctl] Error = EINVAL (#22, Invalid argument): IOCTLError
```

**Comment by prz23** [comment]
The issue has been resolved by changing the pccs_url from `https://localhost:8081/sgx/certification/v3/` to `https://localhost:8081/sgx/certification/v4/` .
