### ISSUE TITLE
[BUG]Resveved Memory modify protection failed

### ISSUE THREAD

**Issue by prz23** [occlum/occlum#1532]
When running a program in Occlum, the following crash occurs. The error varies across different occlum versions, but it seems to be the same issue. How should I handle this error to prevent it from happening? 

# log

in occlunm 0.30.1：
```
/opt/occlum/build/bin/occlum: line 472:   460 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
[ERROR] occlum-pal: Failed to enter the enclave to execute a LibOS thread (host tid = 463) with error code 0x1006: Unknown SGX error (line 21, file src/ocalls/spawn.c)
fatal runtime error: failed to initiate panic, error 5
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
stack backtrace:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Embedded((ENOMEM, "reserved memory modify protection failure")), location: Some(ErrorLocation { line: 142, file: "src/vm/vm_epc.rs" }), cause: None }', src/vm/vm_area.rs:659:14
```

in 0.29.7:
```
/opt/occlum/build/bin/occlum: line 455:   460 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
fatal runtime error: failed to initiate panic, error 5
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
stack backtrace:
thread '<unnamed>' panicked at 'occlum_ocall_mprotect status SGX_SUCCESS., retval -1', src/vm/vm_perms.rs:64:21
```

# Environment
- HW: SGX2
- OS: Ubuntu20.04,
- Occlum version: 0.30.1 and 0.29.7

**Comment by prz23** [comment]
After reviewing the code, in the case of version 0.30.1, if EDMM is enabled, it will not go through the else condition, and thus will not report this error. Would this approach resolve the issue? @jessehui

**Comment by prz23** [comment]
Following your method, I tested it, and it no longer crashes on mprotect fail. Thank you.
