### ISSUE TITLE
[BUG] failed to boot up LibOS: ENOEXEC (#8, Exec format error): unknown executable file format [line = 23, file = src/process/do_spawn/exec_loader.rs] [ERROR] occlum-pal: occlum_ecall_new_process returns ENOEXEC (line 210, file src/pal_api.c)

### ISSUE THREAD

**Issue by Grace-byte912** [occlum/occlum#1536]
# Describe the bug
when I run the rpc code in occlum, it showed this error [ failed to boot up LibOS: ENOEXEC (#8, Exec format error): unknown executable file format [line = 23, file = src/process/do_spawn/exec_loader.rs] [ERROR] occlum-pal: occlum_ecall_new_process returns ENOEXEC (line 210, file src/pal_api.c)]

the core code is :
```python
    elif args.rank == 0:
        print("work0 process init!\n")
        rpc.init_rpc("worker0", rank=args.rank, world_size=args.world_size)
        print("work0 process init finished!\n")

        # Load model
        model = LlamaForCausalLM.from_pretrained(args.model_path)
        model.init_decoders(args.model_path)
        # Load tokenizer
        tokenizer = LlamaTokenizer.from_pretrained(args.model_path, trust_remote_code=True)
        inference(model, args.prompt, tokenizer)
        rpc.shutdown()
    elif args.rank == 1:
        print("work1 process init!\n")
        rpc.init_rpc("worker1", rank=args.rank, world_size=args.world_size)
        print("work1 process init finished!\n")
        rpc.shutdown()
```
# To reproduce
1. bash build_occlum_instance.sh
2. occlum run /bin/python3 /rpc_llm/llama/infer.py --rank 0 --model-path /models/Llama-2-7b-chat-hf

# Expected behavior
The code runs successfully and prints [ work0 process init! ]

# Logs
the detail of logs are below:
[2024-05-08T02:39:39.967Z][ INFO][T0][#0][process] Process created: elf = /bin/init, pid = 1
[2024-05-08T02:39:39.967Z][TRACE][T1][#1][ArchPrctl][syscall] Syscall { num = ArchPrctl, code = 4098, addr = 0x7fa033a94d88 }
[2024-05-08T02:39:39.967Z][DEBUG][T1][#1][ArchPrctl][process] do_arch_prctl: code: ARCH_SET_FS, addr: 0x7fa033a94d88
[2024-05-08T02:39:39.967Z][TRACE][T1][#1][ArchPrctl][syscall] Retval = 0x0
[2024-05-08T02:39:39.967Z][TRACE][T1][#2][SetTidAddress][syscall] Syscall { num = SetTidAddress, tidptr = 0x7fa033a95364 }
[2024-05-08T02:39:39.967Z][DEBUG][T1][#2][SetTidAddress][process] set_tid_address: tidptr: 0x7fa033a95364
[2024-05-08T02:39:39.967Z][TRACE][T1][#2][SetTidAddress][syscall] Retval = 0x1
[2024-05-08T02:39:39.967Z][TRACE][T1][#3][····Open][syscall] Syscall { num = Open, path = 0x7fa035fff8f0, flags = 524288, mode = 0 }
[2024-05-08T02:39:39.967Z][DEBUG][T1][#3][····Open][fs] openat: fs_path: FsPath { Absolute("/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib/libgcc_s.so.1") }, flags: 0o2000000, mode: 0o0
[2024-05-08T02:39:39.967Z][DEBUG][T1][#3][····Open][fs] lookup_inode: cwd: "/", path: "/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib/libgcc_s.so.1"
[2024-05-08T02:39:39.967Z][ERROR][T1][#3][····Open][syscall] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-05-08T02:39:39.967Z][TRACE][T1][#3][····Open][syscall] Retval = 0xfffffffffffffffe
[2024-05-08T02:39:39.967Z][TRACE][T1][#4][····Open][syscall] Syscall { num = Open, path = 0x7fa035fff6a0, flags = 524288, mode = 438 }
[2024-05-08T02:39:39.967Z][DEBUG][T1][#4][····Open][fs] openat: fs_path: FsPath { Absolute("/etc/ld-musl-x86_64.path") }, flags: 0o2000000, mode: 0o666
[2024-05-08T02:39:39.968Z][DEBUG][T1][#4][····Open][fs] lookup_inode: cwd: "/", path: "/etc/ld-musl-x86_64.path"
[2024-05-08T02:39:39.968Z][ERROR][T1][#4][····Open][syscall] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-05-08T02:39:39.968Z][TRACE][T1][#4][····Open][syscall] Retval = 0xfffffffffffffffe
[2024-05-08T02:39:39.968Z][TRACE][T1][#5][····Open][syscall] Syscall { num = Open, path = 0x7fa035fff8f0, flags = 524288, mode = 0 }
[2024-05-08T02:39:39.968Z][DEBUG][T1][#5][····Open][fs] openat: fs_path: FsPath { Absolute("/lib/libgcc_s.so.1") }, flags: 0o2000000, mode: 0o0
[2024-05-08T02:39:39.968Z][DEBUG][T1][#5][····Open][fs] lookup_inode: cwd: "/", path: "/lib/libgcc_s.so.1"
[2024-05-08T02:39:39.968Z][DEBUG][T1][#5][····Open][fs] convert_to_abs_path: cwd: "/", path: "/lib/libgcc_s.so.1"
[2024-05-08T02:39:39.968Z][DEBUG][T1][#5][····Open][fs] openat: result fd: 3

# Environment

- HW: SGX2]
- OS: Ubuntu22.04
- Occlum version: [e.g. 0.28.0]

**Comment by qzheng527** [comment]
> when I run the rpc code in occlum, it showed this error [ failed to boot up LibOS: ENOEXEC (https://github.com/occlum/occlum/pull/8, Exec format error): unknown executable file format [line = 23, file = src/process/do_spawn/exec_loader.rs] [ERROR] occlum-pal: occlum_ecall_new_process returns ENOEXEC (line 210, file src/pal_api.c)]
That means your entrypoint **/bin/python3** is not PIE format executable binary.
Please follow our python demo to install the python binanry with conda.

**Comment by Grace-byte912** [comment]
I follow the demo of bigdl-llm, here is the install_python_with_conda.sh:
```bash
#!/bin/bash
set -e
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" >/dev/null 2>&1 && pwd )"

# Install python and dependencies to specified position
[ -f Miniconda3-latest-Linux-x86_64.sh ] || wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
[ -d miniconda ] || bash ./Miniconda3-latest-Linux-x86_64.sh -b -p $script_dir/miniconda
$script_dir/miniconda/bin/conda create \
            --prefix $script_dir/python-occlum -y \
                python=3.11

$script_dir/python-occlum/bin/pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu
$script_dir/python-occlum/bin/pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by qzheng527** [comment]
> python=3.11

Not all python version are built in PIE mode. You could check that by `file <path>/<binary>`.
That is why we specify the python version in our demo.
`python=3.9.11`.

**Comment by Grace-byte912** [comment]
thanks，I solved this problem but here is another one.
When I run a python RPC process trying to connect with another process running in normal cpu environment, how can I solve this? 
```
root@tee-node35:/home/llm/rpc_llm/occlum_instance# occlum exec  /bin/python3 /llama/infer.py --rank 0 
work0 process init!

Traceback (most recent call last):
  File "/llama/infer.py", line 107, in <module>
    rpc.init_rpc("worker0", rank=args.rank, world_size=args.world_size)
  File "/opt/python-occlum/lib/python3.10/site-packages/torch/distributed/rpc/__init__.py", line 199, in init_rpc
    _init_rpc_backend(backend, store, name, rank, world_size, rpc_backend_options)
  File "/opt/python-occlum/lib/python3.10/site-packages/torch/distributed/rpc/__init__.py", line 234, in _init_rpc_backend
    rpc_agent = backend_registry.init_backend(
  File "/opt/python-occlum/lib/python3.10/site-packages/torch/distributed/rpc/backend_registry.py", line 104, in init_backend
    return backend.value.init_backend_handler(*args, **kwargs)
  File "/opt/python-occlum/lib/python3.10/site-packages/torch/distributed/rpc/backend_registry.py", line 357, in _tensorpipe_init_backend_handler
    api._init_rpc_states(agent)
  File "/opt/python-occlum/lib/python3.10/site-packages/torch/distributed/rpc/api.py", line 119, in _init_rpc_states
    _set_and_start_rpc_agent(agent)
RuntimeError: In create at tensorpipe/transport/shm/context_impl.cc:36 "!bootID.has_value()Unable to read boot_id"
Error: 256
```

**Comment by qzheng527** [comment]
@Grace-byte912 The filesystem in Occlum is totally isolated with that in host fs. There are only limited /proc nodes exported in Occlum FS such as /proc/cpuinfo, /proc/meminfo, etc.  For your case, the boot_id is not existed in Occlum FS.
For more details about Occlum FS, please refer to https://occlum.readthedocs.io/en/latest/filesystem/fs_overview.html

**Comment by Grace-byte912** [comment]
got it. Thanks for answering.
