### ISSUE TITLE
[BUG]Cannot import concrete-ml and concrete-python library

### ISSUE THREAD

**Issue by thempp66** [occlum/occlum#1564]
# Describe the bug
Follow the instruction of python demo,  I setup the enviornment. But I use pip to install concrete-ml lib because the lib cannot be found in conda repo. Finally I got the error.
lib addr: [concrete-python](https://github.com/zama-ai/concrete) [concrete-ml](https://github.com/zama-ai/concrete-ml)

# To reproduce
1. git clone https://github.com/occlum/occlum.git
2. cd /occlum/demos/python/python_glibc
3. bash ./install_python_with_conda.sh
4. ./python-occlum/bin/pip3 install -U pip wheel setuptools && ./python-occlum/bin/pip3 install concrete-python
5. bash ./run_python_on_occlum.sh
6. adjust the Occlum.json and run the python code below: occlum run /bin/python3 ml.py
```
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from concrete.ml.sklearn import LogisticRegression

# Lets create a synthetic data-set
x, y = make_classification(n_samples=100, class_sep=2, n_features=30, random_state=42)

# Split the data-set into a train and test set
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# Now we train in the clear and quantize the weights
model = LogisticRegression(n_bits=8)
model.fit(X_train, y_train)

# We can simulate the predictions in the clear
y_pred_clear = model.predict(X_test)

# We then compile on a representative set 
model.compile(X_train)

# Finally we run the inference on encrypted inputs !
y_pred_fhe = model.predict(X_test, fhe="execute")

print("In clear  :", y_pred_clear)
print("In FHE    :", y_pred_fhe)
print(f"Similarity: {int((y_pred_fhe == y_pred_clear).mean()*100)}%")

```

# Expected behavior
output
```
    In clear  : [0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
    In FHE    : [0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
    Similarity: 100%
```

# Logs
```
root@0df33025341d:/repo/tmp/occlum/demos/python/python_glibc/occlum_instance# occlum run /bin/python3 ml.py
Traceback (most recent call last):
  File "ml.py", line 29, in <module>
    from concrete.ml.sklearn import LogisticRegression
  File "/opt/python-occlum/lib/python3.8/site-packages/concrete/ml/sklearn/__init__.py", line 10, in <module>
    from .base import (
  File "/opt/python-occlum/lib/python3.8/site-packages/concrete/ml/sklearn/base.py", line 17, in <module>
    import brevitas.nn as qnn
  File "/opt/python-occlum/lib/python3.8/site-packages/brevitas/__init__.py", line 12, in <module>
    from torch.utils import cpp_extension
  File "/opt/python-occlum/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
    from .hipify import hipify_python
  File "/opt/python-occlum/lib/python3.8/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
    from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
  File "/opt/python-occlum/lib/python3.8/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
  File "/opt/python-occlum/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/python-occlum/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/python-occlum/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/python-occlum/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 38] Function not implemented
```

# Environment

- HW: SGX2, 32GB SGX memory + 32GB memory
- OS: Ubuntu 20.04.5
- Occlum version: 0.29.5

**Comment by qzheng527** [comment]
@thempp66 Occlum doesn't support fork syscall. Please try conda with python 3.10.0 which the subprocess will use posix_spawn instead.

**Comment by thempp66** [comment]
> @thempp66 Occlum doesn't support fork syscall. Please try conda with python 3.10.0 which the subprocess will use posix_spawn instead.

OK, thanks. I will try. By the way, can I use pip to install the lib to python-occlum directory directly? The lib concrete-ml cannot be found in conda.

**Comment by qzheng527** [comment]
> > @thempp66 Occlum doesn't support fork syscall. Please try conda with python 3.10.0 which the subprocess will use posix_spawn instead.
> 
> OK, thanks. I will try. By the way, can I use pip to install the lib to python-occlum directory directly? The lib concrete-ml cannot be found in conda.

Yes, you can. Check below demo for reference.
https://github.com/occlum/occlum/blob/master/demos/bigdl-llm/install_python_with_conda.sh#L13

**Comment by thempp66** [comment]
> @thempp66 Occlum doesn't support fork syscall. Please try conda with python 3.10.0 which the subprocess will use posix_spawn instead.

After I use python3.10.0 and run the same demo. It appears two kinds of error.
```
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//ml.py", line 1, in <module>
    from sklearn.datasets import make_classification
  File "/opt/python-occlum/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/opt/python-occlum/lib/python3.10/site-packages/sklearn/base.py", line 13, in <module>
    import numpy as np
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from ""
  * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"
```

```
Traceback (most recent call last):
  File "//ml.py", line 1, in <module>
    from sklearn.datasets import make_classification
  File "/opt/python-occlum/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/opt/python-occlum/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/opt/python-occlum/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 22, in <module>
    from scipy.sparse import issparse
  File "/opt/python-occlum/lib/python3.10/site-packages/scipy/sparse/__init__.py", line 283, in <module>
    from . import csgraph
  File "/opt/python-occlum/lib/python3.10/site-packages/scipy/sparse/csgraph/__init__.py", line 185, in <module>
    from ._laplacian import laplacian
  File "/opt/python-occlum/lib/python3.10/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/opt/python-occlum/lib/python3.10/site-packages/scipy/sparse/linalg/__init__.py", line 120, in <module>
    from ._isolve import *
  File "/opt/python-occlum/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/__init__.py", line 4, in <module>
    from .iterative import *
  File "/opt/python-occlum/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/iterative.py", line 9, in <module>
    from . import _iterative
ImportError: libopenblasp-r0-41284840.3.18.so: failed to map segment from shared object
```

**Comment by thempp66** [comment]
A simpler example: I write `$script_dir/miniconda/bin/conda create --prefix $script_dir/python-occlum -y python=3.10.0 scikit-learn` in install_python_with_conda.sh to install skelarn and python. And then I import sklearn `from sklearn.datasets import make_classification`. The similar error occur.
```
OpenBLAS blas_thread_init: pthread_create failed for thread 37 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 38 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 39 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 40 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 41 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 42 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 43 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 44 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 45 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 64 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 65 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 66 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 67 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 68 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 69 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 70 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 71 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 72 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 73 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 74 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 75 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 76 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 77 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 78 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 79 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 80 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 81 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 82 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 83 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 84 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 85 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 86 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 87 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 88 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 89 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 90 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 91 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 92 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 93 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 94 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 95 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 96 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 97 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 98 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 99 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 100 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 101 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 102 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 103 of 104: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from ""
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//ml.py", line 1, in <module>
    from sklearn.datasets import make_classification
  File "/opt/python-occlum/lib/python3.10/site-packages/sklearn/__init__.py", line 87, in <module>
    from .base import clone
  File "/opt/python-occlum/lib/python3.10/site-packages/sklearn/base.py", line 14, in <module>
    import numpy as np
  File "/opt/python-occlum/lib/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by qzheng527** [comment]
@thempp66 It was because the thread  number required was bigger than the limit **max_num_of_threads** defined in the Occlum.json.
You could:
1. increase the **max_num_of_threads**
2. limit the openblas threads number by setting env **OPENBLAS_NUM_THREADS** in Occlum.

**Comment by thempp66** [comment]
Thanks, @qzheng527 
I set max_num_of_threads = 512, OPENBLAS_NUM_THREADS=1 in Occlum.json, now it works well with sklearn lib. But it still dosen't work when importing concrete-ml lib. There is only one error left:
```
Traceback (most recent call last):
  File "//ml.py", line 3, in <module>
    from concrete.ml.sklearn import LogisticRegression
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/ml/sklearn/__init__.py", line 4, in <module>
    from ..common.debugging.custom_assert import assert_true
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/ml/common/__init__.py", line 2, in <module>
    from . import check_inputs, debugging, utils
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/ml/common/utils.py", line 11, in <module>
    import torch
  File "/opt/python-occlum/lib/python3.10/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: libtorch_cuda_cu.so: failed to map segment from shared object
```

**Comment by thempp66** [comment]
It import the lib successfully when I set a larger memory in Occum.json.
But it occur another error. It seems that the problem may be about memory allocation. If so, how can I make sure the memory is enough?
Below is the error info:
```
root@1573bd9c8ff3:/repo/occlum/demos/python/python_glibc/occlum_instance# occlum run /bin/python3 ml.py
Traceback (most recent call last):
  File "//ml.py", line 21, in <module>
    model.compile(X_train)
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/ml/sklearn/base.py", line 564, in compile
    self.fhe_circuit_ = module_to_compile.compile(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 583, in compile
    circuit = Circuit(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/circuit.py", line 63, in __init__
    self.enable_fhe_execution()
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/circuit.py", line 129, in enable_fhe_execution
    self.server = Server.create(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/server.py", line 206, in create
    compilation_result = support.compile(mlir, options, compilation_context)
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/compiler/library_support.py", line 172, in compile
    self.cpp().compile(
RuntimeError: Can't emit artifacts: Cannot allocate memory
Cannot call the linker: ld --shared -o /tmp/tmpvlap__vw/sharedlib.so /tmp/tmpvlap__vw/program.module-0.mlir.o /opt/python-occlum/lib/python3.10/site-packages/concrete_python.libs/libConcretelangRuntime-9b345fb1.so -rpath=/opt/python-occlum/lib/python3.10/site-packages/concrete_python.libs --disable-new-dtags 2>&1
```

**Comment by thempp66** [comment]
The issue is solved and I will open a new issue.
