### ISSUE TITLE
[BUG]thread '<unnamed>' panicked at 'explicit panic', src/config.rs:24:17

### ISSUE THREAD

**Issue by joaquinboss** [occlum/occlum#1569]
# Describe the bug
when the command 'occlum run' is executed, it occur bug
```
hread '<unnamed>' panicked at 'explicit panic', src/config.rs:24:17
/opt/occlum/build/bin/occlum: line 472: 47234 Illegal instruction    (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"

```
# To reproduce
1. occlum init
2. occlum build 
3. occlum run

# Expected behavior
program run successfully

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW: [e.g. SGX1,SGX_LC] 
- OS: [e.g. Ubuntu20.04]
- Occlum version: [e.g. 0.28.0]

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

Please help me. Expert, I will appreciate it.

**Comment by qzheng527** [comment]
@joaquinboss First, check your Occlum.json if anything wrong compared with the one in demos. If nothing found, try enable the Occlum log by OCCLUM_LOG_LEVEL=trace occlum run ....

**Comment by joaquinboss** [comment]
@qzheng527 OK, thank you. Can you look another issue? I will appreciate it.
[https://github.com/occlum/occlum/issues/1579](url)
