### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wang12060** [occlum/occlum#1574]
# Describe the bug

# To reproduce
1. occlum new occlum-instance
2. occlum build
3. occlum run

# Expected behavior

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW:  SGX1
- OS: Ubuntu20.04
- Occlum version:  0.30.1

# Additional context
使用occlum运行一个python程序，只是输出一个hello world时，可以正常运行，但是加入import pandas as pd就有如下报错：
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /tmp/deb_build/occlum-0.30.1/occlum-src/deps/sefs/rcore-fs-unionfs/src/lib.rs:543:24
stack backtrace:
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum：行 472: 52040 非法指令            （核心已转储） RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"

有没有也遇到这个问题，希望能得到解答！！！
# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by joaquinboss** [comment]
可以看下是不是程序里面有读取数据集这一步，有的话检查下路径是否出错【非官方人士】

**Comment by wang12060** [comment]
> 可以看下是不是程序里面有读取数据集这一步，有的话检查下路径是否出错【非官方人士】

应该不是，我只写了两行代码：import pandas as pd

**Comment by wang12060** [comment]
> 可以看下是不是程序里面有读取数据集这一步，有的话检查下路径是否出错【非官方人士】

谢谢你的回答！但应该不是，因为我只写了两行代码：import pandas as pd
print("Hello world!")

**Comment by joaquinboss** [comment]
> > 可以看下是不是程序里面有读取数据集这一步，有的话检查下路径是否出错【非官方人士】
> 
> 谢谢你的回答！但应该不是，因为我只写了两行代码：import pandas as pd print("Hello world!")

客气，你可以问问GPT，我觉得多半是配置文件occlum.json你需要做些修改
而且occlum里面python的包和依赖很容易有版本冲突的问题

**Comment by qzheng527** [comment]
@wang12060 You can refer to [demo](https://github.com/occlum/occlum/blob/master/demos/python/python_glibc/demo.py#L1) which also use pandas as well.

**Comment by wang12060** [comment]
> @wang12060 You can refer to [demo](https://github.com/occlum/occlum/blob/master/demos/python/python_glibc/demo.py#L1) which also use pandas as well.

I try it, but also have this error.

**Comment by wang12060** [comment]
我尝试修改了occlum.json文件中的kernel_space_heap_size为32MB，之前的报错没有了但是出现了新的错误：Traceback (most recent call last):
  File "/root/hello.py", line 1, in <module>
    import pandas as pd
  File "/opt/python-occlum/lib/python3.8/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/opt/python-occlum/lib/python3.8/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/opt/python-occlum/lib/python3.8/site-packages/numpy/core/__init__.py", line 98, in <module>
    from . import _add_newdocs
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 980, in get_code
  File "<frozen importlib._bootstrap_external>", line 1038, in get_data
OSError: [Errno 5] Input/output error

**Comment by wang12060** [comment]
执行一次occlum build后，第一次执行occlum run /bin/python3 /root/hello.py报错：
Traceback (most recent call last):
  File "/root/hello.py", line 1, in <module>
    import pandas as pd
  File "/opt/python-occlum/lib/python3.8/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/opt/python-occlum/lib/python3.8/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/opt/python-occlum/lib/python3.8/site-packages/numpy/core/__init__.py", line 98, in <module>
    from . import _add_newdocs
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 980, in get_code
  File "<frozen importlib._bootstrap_external>", line 1038, in get_data
OSError: [Errno 5] Input/output error
第二次执行occlum run /bin/python3 /root/hello.py报错：
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /tmp/deb_build/occlum-0.30.1/occlum-src/deps/sefs/rcore-fs-unionfs/src/lib.rs:543:24
stack backtrace:
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum：行 472: 24758 非法指令            （核心已转储） RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"

**Comment by joaquinboss** [comment]
@wang12060 大佬，我也是在研究occlum的，方便交流一下吗？email: 1420654694@qq.com

**Comment by wang12060** [comment]
> @wang12060 大佬，我也是在研究occlum的，方便交流一下吗？email: [1420654694@qq.com](mailto:1420654694@qq.com)

可以的，互相学习！2770163662@qq.com

**Comment by Xxxgrey** [comment]
你好我也遇到类似的 问题 但我是occlum run /bin/python3 eval.py
Traceback (most recent call last):
  File "//eval.py", line 4, in <module>
    from torchvision import datasets, transforms
  File "/opt/python-occlum/lib/python3.9/site-packages/torchvision/__init__.py", line 10, in <module>
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/occlum/deps/sefs/rcore-fs-unionfs/src/lib.rs:543:24
这个torchvision报错 请问大佬解决了吗

**Comment by wang12060** [comment]
你好！
&nbsp; &nbsp; &nbsp; 这个报错是import才报错的，我认为可能有2个原因：
&nbsp; &nbsp;1. 底层库的配置有问题，是不是存在库和库之间互相冲突不支持的情况；
&nbsp; &nbsp;2. 分配的权限不足。
或许你可以尝试能否用其他的库进行代替。
或者可以逐行调试代码。
也可能是因为允许打开的文件不够多，如果是linux系统的话，可以使用ulimit -n 命令进行查看调整。
希望对你有帮助！


我最近使用的时候也遇到了一个问题，
我用相同的方法构建了一个Python库，在使用occlum运行代码时会显示连接不到python3。可以给我一个你构建occlum 实例的步骤吗？
感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "occlum/occlum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月19日(星期三) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [occlum/occlum] [BUG] (Issue #1574)



   
你好我也遇到类似的 问题 但我是occlum run /bin/python3 eval.py
 Traceback (most recent call last):
 File "//eval.py", line 4, in 
 from torchvision import datasets, transforms
 File "/opt/python-occlum/lib/python3.9/site-packages/torchvision/init.py", line 10, in 
 thread '' panicked at 'called Option::unwrap() on a None value', /root/occlum/deps/sefs/rcore-fs-unionfs/src/lib.rs:543:24
 这个torchvision报错 请问大佬解决了吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  Xxxgrey left a comment (occlum/occlum#1574)
 
你好我也遇到类似的 问题 但我是occlum run /bin/python3 eval.py
 Traceback (most recent call last):
 File "//eval.py", line 4, in 
 from torchvision import datasets, transforms
 File "/opt/python-occlum/lib/python3.9/site-packages/torchvision/init.py", line 10, in 
 thread '' panicked at 'called Option::unwrap() on a None value', /root/occlum/deps/sefs/rcore-fs-unionfs/src/lib.rs:543:24
 这个torchvision报错 请问大佬解决了吗

**Comment by Xxxgrey** [comment]
> 你好！
> &nbsp; &nbsp; &nbsp; 这个报错是import才报错的，我认为可能有2个原因：
> &nbsp; &nbsp;1. 底层库的配置有问题，是不是存在库和库之间互相冲突不支持的情况；
> &nbsp; &nbsp;2. 分配的权限不足。
> 或许你可以尝试能否用其他的库进行代替。
> 或者可以逐行调试代码。
> 也可能是因为允许打开的文件不够多，如果是linux系统的话，可以使用ulimit -n 命令进行查看调整。
> 希望对你有帮助！
> 
> 
> 我最近使用的时候也遇到了一个问题，
> 我用相同的方法构建了一个Python库，在使用occlum运行代码时会显示连接不到python3。可以给我一个你构建occlum 实例的步骤吗？
> 感谢！
> […](#)

你好这是我提交的issue里面 有每一个我配置的步骤
https://github.com/occlum/occlum/issues/1664

**Comment by Xxxgrey** [comment]
> 你好！
> &nbsp; &nbsp; &nbsp; 这个报错是import才报错的，我认为可能有2个原因：
> &nbsp; &nbsp;1. 底层库的配置有问题，是不是存在库和库之间互相冲突不支持的情况；
> &nbsp; &nbsp;2. 分配的权限不足。
> 或许你可以尝试能否用其他的库进行代替。
> 或者可以逐行调试代码。
> 也可能是因为允许打开的文件不够多，如果是linux系统的话，可以使用ulimit -n 命令进行查看调整。
> 希望对你有帮助！
> 
> 
> 我最近使用的时候也遇到了一个问题，
> 我用相同的方法构建了一个Python库，在使用occlum运行代码时会显示连接不到python3。可以给我一个你构建occlum 实例的步骤吗？
> 感谢！
> […](#)

大佬方便留一个联系方式吗，有些问题想请教
