### ISSUE TITLE
[BUG]RuntimeError: Can't emit artifacts: Cannot allocate memory

### ISSUE THREAD

**Issue by thempp66** [occlum/occlum#1580]
# Describe the bug
Error when runing machine leanring traning example. [demo](https://github.com/zama-ai/concrete-ml)

# To reproduce
1. git clone https://github.com/occlum/occlum.git
2. cd /occlum/demos/python/python_glibc
3. bash ./install_python_with_conda.sh
4. ./python-occlum/bin/pip3 install -U pip wheel setuptools && ./python-occlum/bin/pip3 install concrete-python
5. bash ./run_python_on_occlum.sh
6. adjust the Occlum.json and run the python code below: occlum run /bin/python3 ml.py
```
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from concrete.ml.sklearn import LogisticRegression

# Lets create a synthetic data-set
x, y = make_classification(n_samples=100, class_sep=2, n_features=30, random_state=42)

# Split the data-set into a train and test set
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# Now we train in the clear and quantize the weights
model = LogisticRegression(n_bits=8)
model.fit(X_train, y_train)

# We can simulate the predictions in the clear
y_pred_clear = model.predict(X_test)

# We then compile on a representative set 
model.compile(X_train)

# Finally we run the inference on encrypted inputs !
y_pred_fhe = model.predict(X_test, fhe="execute")

print("In clear  :", y_pred_clear)
print("In FHE    :", y_pred_fhe)
print(f"Similarity: {int((y_pred_fhe == y_pred_clear).mean()*100)}%")

# Output:
    # In clear  : [0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
    # In FHE    : [0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
    # Similarity: 100%
```

occlum.json :
```
{
  "resource_limits": {
    "kernel_space_heap_size": "32GB",
    "kernel_space_stack_size": "1MB",
    "user_space_size": "8GB",
    "max_num_of_threads": 512,
    "user_space_max_size": "8GB",
    "kernel_space_heap_max_size": "32GB"
  },
  "process": {
    "default_stack_size": "4MB",
    "default_heap_size": "32MB",
    "default_mmap_size": "100MB"
  },
  "entry_points": [
    "/bin"
  ],
  "env": {
    "default": [
      "OCCLUM=yes",
      "PYTHONHOME=/opt/python-occlum",
      "OPENBLAS_NUM_THREADS=1",
      "USE_RTLD_GLOBAL_WITH_LIBTORCH=false",
      "USE_GLOBAL_DEPS=false"
    ],
    "untrusted": [
      "EXAMPLE"
    ]
  },
  "metadata": {
    "product_id": 0,
    "version_number": 0,
    "debuggable": true,
    "enable_kss": false,
    "family_id": {
      "high": "0x0",
      "low": "0x0"
    },
    "ext_prod_id": {
      "high": "0x0",
      "low": "0x0"
    },
    "pkru": 0
  },
  "mount": [
    {
      "target": "/",
      "type": "unionfs",
      "options": {
        "layers": [
          {
            "target": "/",
            "type": "sefs",
            "source": "./build/mount/__ROOT",
            "options": {
              "MAC": ""
            }
          },
          {
            "target": "/",
            "type": "sefs",
            "source": "./run/mount/__ROOT"
          }
        ]
      }
    },
    {
      "target": "/host",
      "type": "hostfs",
      "source": "."
    },
    {
      "target": "/proc",
      "type": "procfs"
    },
    {
      "target": "/dev",
      "type": "devfs"
    }
  ]
}

```

# Expected behavior
```
    In clear  : [0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
    In FHE    : [0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
    Similarity: 100%
```

# Logs
```
[2024-06-27T08:39:42.683Z][ERROR][T2][#59297][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.687Z][ERROR][T2][#59318][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.687Z][ERROR][T2][#59328][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.688Z][ERROR][T2][#59340][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.732Z][ERROR][T2][#59400][··Openat] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-06-27T08:39:42.806Z][ERROR][T2][#59459][Getrandom] Error = EINVAL (#22, Invalid argument): invalid flags [line = 845, file = src/syscall/mod.rs]
[2024-06-27T08:39:42.806Z][ERROR][T2][#59461][Getrandom] Error = EFAULT (#14, Bad address): the whole buffer is not in the user space [line = 33, file = src/util/mem_util.rs]
[2024-06-27T08:39:42.806Z][ERROR][T2][#59464] Error = EINVAL (#22, Invalid argument): Invalid system call number (332) [line = 504, file = src/syscall/mod.rs]
[2024-06-27T08:39:42.806Z][ERROR][T2][#59465] Error = EINVAL (#22, Invalid argument): Invalid system call number (332) [line = 504, file = src/syscall/mod.rs]
[2024-06-27T08:39:42.806Z][ERROR][T2][#59466][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-06-27T08:39:42.806Z][ERROR][T2][#59468][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-06-27T08:39:42.806Z][ERROR][T2][#59470][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-06-27T08:39:42.806Z][ERROR][T2][#59472][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-06-27T08:39:42.810Z][ERROR][T2][#59493][·····Brk] New brk address is too high
[2024-06-27T08:39:42.829Z][ERROR][T2][#59756][·····Brk] New brk address is too high
[2024-06-27T08:39:42.843Z][ERROR][T2][#59758][·····Brk] New brk address is too high
[2024-06-27T08:39:42.847Z][ERROR][T2][#59804][···Mkdir] Error = EEXIST (#17, File exists):  [line = 14, file = src/fs/file_ops/mkdir.rs]
[2024-06-27T08:39:42.847Z][ERROR][T2][#59808][SpawnGlibc] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-06-27T08:39:42.875Z][ERROR][T2][#59838][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.875Z][ERROR][T2][#59844][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 112, file = src/fs/pipe.rs]
[2024-06-27T08:39:42.875Z][ERROR][T2][#59845][···Lseek] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
[2024-06-27T08:39:42.875Z][ERROR][T2][#59846][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 112, file = src/fs/pipe.rs]
[2024-06-27T08:39:42.876Z][ERROR][T105][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.876Z][ERROR][T109][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.876Z][ERROR][T85][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.876Z][ERROR][T106][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T78][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T2][#59924][··Execve] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-06-27T08:39:42.877Z][ERROR][T119][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T116][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T94][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T121][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T98][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T99][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T118][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T86][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.877Z][ERROR][T100][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T2][#59936][···Wait4] Error = ECHILD (#10, No child processes): Cannot find any unwaited children [line = 57, file = src/process/do_wait4.rs]
[2024-06-27T08:39:42.878Z][ERROR][T88][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T87][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T2][#59938][···Wait4] Error = ECHILD (#10, No child processes): Cannot find any unwaited children [line = 57, file = src/process/do_wait4.rs]
[2024-06-27T08:39:42.878Z][ERROR][T73][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T103][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T75][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T96][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T77][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T107][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T72][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T95][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T102][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T81][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T101][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T71][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T115][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T97][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T93][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T90][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T112][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.878Z][ERROR][T76][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T79][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T74][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T104][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T92][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T89][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T111][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T83][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T117][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T82][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T108][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T114][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T91][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T84][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T120][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T2][#59943][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.879Z][ERROR][T80][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T113][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T2][#59948][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 112, file = src/fs/pipe.rs]
[2024-06-27T08:39:42.879Z][ERROR][T110][#2][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.879Z][ERROR][T2][#59949][···Lseek] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
[2024-06-27T08:39:42.880Z][ERROR][T2][#60025][··Execve] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2024-06-27T08:39:42.881Z][ERROR][T119][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T105][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T106][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T109][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T85][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T94][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T98][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T121][#4][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T116][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T86][#3][···Futex] Error = EINTR (#4, Interrupted system call): futex wait timeout or interrupted [line = 294, file = src/process/do_futex.rs]
[2024-06-27T08:39:42.881Z][ERROR][T2][#60036][···Wait4] Error = ECHILD (#10, No child processes): Cannot find any unwaited children [line = 57, file = src/process/do_wait4.rs]
[2024-06-27T08:39:42.882Z][ERROR][T2][#60038][···Wait4] Error = ECHILD (#10, No child processes): Cannot find any unwaited children [line = 57, file = src/process/do_wait4.rs]
[2024-06-27T08:39:42.883Z][ERROR][T2][#60042][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.884Z][ERROR][T2][#60049][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.885Z][ERROR][T2][#60056][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.886Z][ERROR][T2][#60063][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.887Z][ERROR][T2][#60070][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.888Z][ERROR][T2][#60077][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.919Z][ERROR][T2][#60084][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.919Z][ERROR][T2][#60095][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
[2024-06-27T08:39:42.920Z][ERROR][T2][#60107][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 243, file = src/fs/inode_file.rs]
Traceback (most recent call last):
  File "//ml.py", line 21, in <module>
    model.compile(X_train)
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/ml/sklearn/base.py", line 564, in compile
    self.fhe_circuit_ = module_to_compile.compile(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 583, in compile
    circuit = Circuit(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/circuit.py", line 63, in __init__
    self.enable_fhe_execution()
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/circuit.py", line 129, in enable_fhe_execution
    self.server = Server.create(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/server.py", line 206, in create
    compilation_result = support.compile(mlir, options, compilation_context)
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/compiler/library_support.py", line 172, in compile
    self.cpp().compile(
RuntimeError: Can't emit artifacts: Cannot allocate memory
Cannot call the linker: ld --shared -o /tmp/tmplp9fzv3q/sharedlib.so /tmp/tmplp9fzv3q/program.module-0.mlir.o /opt/python-occlum/lib/python3.10/site-packages/concrete_python.libs/libConcretelangRuntime-9b345fb1.so -rpath=/opt/python-occlum/lib/python3.10/site-packages/concrete_python.libs --disable-new-dtags 2>&1
[2024-06-27T08:39:43.486Z][ERROR][T117][#4][·Madvise] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 973, file = src/syscall/mod.rs]
[2024-06-27T08:39:43.487Z][ERROR][T97][#4][·Madvise] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 973, file = src/syscall/mod.rs]
[2024-06-27T08:39:43.487Z][ERROR][T82][#4][·Madvise] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 973, file = src/syscall/mod.rs]
[2024-06-27T08:39:43.487Z][ERROR][T94][#5][·Madvise] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 973, file = src/syscall/mod.rs]
[2024-06-27T08:39:43.487Z][ERROR][T113][#4][·Madvise] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 973, file = src/syscall/mod.rs]
[2024-06-27T08:39:43.487Z][ERROR][T110][#4][·Madvise] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 973, file = src/syscall/mod.rs]
```

# Environment

- HW: SGX2, 32GB SGX memory + 32GB memory
- OS: Ubuntu 20.04.5
- Occlum version: 0.29.5

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by thempp66** [comment]
Hello, I think I found the reason of error. Could you teach me how to mount `/tmp` to occlum? Is that something like this? I am not sure about the type of mount.
```
        {
            "target": "/tmp",
            "type": "tmpfs"
        },
```
