### ISSUE TITLE
[BUG]Cannot link lib or mount /tmp

### ISSUE THREAD

**Issue by thempp66** [occlum/occlum#1589]
# Describe the bug
The error shows `Cannot call the linker`. According to another [issue](https://github.com/gramineproject/gramine/issues/1932) have been solved, I guess it is something to do with mount. I tried to mount `/tmp` as what the solution (of the issue I mentioned before) do, but it still doesn't work. I am not sure if I mount the `/tmp` file in a correct way. Or is there any other resaon that cause this error? Looking forward to your help! It is really important to our project! Thanks!

# To reproduce
use below config and run occlum build
```
{
  "resource_limits": {
    "kernel_space_heap_size": "2GB",
    "kernel_space_stack_size": "1MB",
    "user_space_size": "2GB",
    "max_num_of_threads": 512,
    "user_space_max_size": "8GB",
    "kernel_space_heap_max_size": "32GB"
  },
  "process": {
    "default_stack_size": "4MB",
    "default_heap_size": "32MB",
    "default_mmap_size": "100MB"
  },
  "entry_points": [
    "/bin"
  ],
  "env": {
    "default": [
      "OCCLUM=yes",
      "PYTHONHOME=/opt/python-occlum",
      "OPENBLAS_NUM_THREADS=1",
      "USE_RTLD_GLOBAL_WITH_LIBTORCH=false",
      "USE_GLOBAL_DEPS=false",
      "PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "PYTHONHOME=/opt/python-occlum"
    ],
    "untrusted": [
      "EXAMPLE"
    ]
  },
  "metadata": {
    "product_id": 0,
    "version_number": 0,
    "debuggable": true,
    "enable_kss": false,
    "family_id": {
      "high": "0x0",
      "low": "0x0"
    },
    "ext_prod_id": {
      "high": "0x0",
      "low": "0x0"
    }
  },
  "feature": {
      "amx": 0,
      "pkru": 0,
      "enable_edmm": false,
      "enable_posix_shm": false
  },
  "mount": [
    {
      "target": "/",
      "type": "unionfs",
      "options": {
        "layers": [
          {
            "target": "/",
            "type": "sefs",
            "source": "./build/mount/__ROOT",
            "options": {
              "MAC": ""
            }
          },
          {
            "target": "/",
            "type": "sefs",
            "source": "./run/mount/__ROOT"
          }
        ]
      }
    },
    {
      "target": "/tmp",
      "type": "hostfs",
      "source": "/tmp"
    },
    {
      "target": "/dev",
      "type": "devfs"
    }
  ]
}

```

code:
```
import time
start_time = time.time()
print("log00 : ", (time.time() - start_time) * 1000)
from sklearn.datasets import make_classification
print("log01 : ", (time.time() - start_time) * 1000)
from sklearn.model_selection import train_test_split
print("log02 : ", (time.time() - start_time) * 1000)
from concrete.ml.sklearn import LogisticRegression
print("log03 : ", (time.time() - start_time) * 1000)

# Lets create a synthetic data-set
x, y = make_classification(n_samples=100, class_sep=2, n_features=30, random_state=42)
print("log2 : ", (time.time() - start_time) * 1000)
# Split the data-set into a train and test set
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)
print("log3 : ", (time.time() - start_time) * 1000)
# Now we train in the clear and quantize the weights
model = LogisticRegression(n_bits=8)
print("log4 : ", (time.time() - start_time) * 1000)

model.fit(X_train, y_train)
print("log5 : ", (time.time() - start_time) * 1000)

# We can simulate the predictions in the clear
y_pred_clear = model.predict(X_test)
print("log6 : ", (time.time() - start_time) * 1000)

# We then compile on a representative set
model.compile(X_train)
print("log7 : ", (time.time() - start_time) * 1000)

# Finally we run the inference on encrypted inputs !
y_pred_fhe = model.predict(X_test, fhe="execute")
print("log8 : ", (time.time() - start_time) * 1000)

print("In clear  :", y_pred_clear)
print("In FHE    :", y_pred_fhe)
print(f"Similarity: {int((y_pred_fhe == y_pred_clear).mean()*100)}%")

```

# Expected behavior
```
In clear  : [0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
In FHE    : [0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
Similarity: 100%
```

# Logs
This is the full debug log: 
[log.txt](https://github.com/user-attachments/files/16173968/log.txt)

Below is the error log:
```
[2024-07-11T08:25:54.354Z][ERROR][T2][#16][ArchPrctl][syscall] Error = EINVAL (#22, Invalid argument): Unknown code for arch_prctl [line = 60, file = src/process/do_arch_prctl.rs]
[2024-07-11T08:25:54.377Z][ERROR][T2][#189][Readlink][syscall] Error = EINVAL (#22, Invalid argument): not a symbolic link [line = 14, file = src/fs/file_ops/symlink.rs]
[2024-07-11T08:25:54.429Z][ERROR][T2][#360][···Lseek][syscall] Error = ESPIPE (#29, Illegal seek): libc error [line = 430, file = src/fs/stdio.rs]
[2024-07-11T08:25:54.429Z][ERROR][T2][#366][···Lseek][syscall] Error = ESPIPE (#29, Illegal seek): libc error [line = 240, file = src/fs/stdio.rs]
[2024-07-11T08:25:54.429Z][ERROR][T2][#372][···Lseek][syscall] Error = ESPIPE (#29, Illegal seek): libc error [line = 240, file = src/fs/stdio.rs]
[2024-07-11T08:25:54.487Z][ERROR][T2][#721][Readlink][syscall] Error = EINVAL (#22, Invalid argument): not a symbolic link [line = 14, file = src/fs/file_ops/symlink.rs]
log00 :  0.008821487426757812
[2024-07-11T08:25:55.485Z][ERROR][T2][#6333][··Openat][syscall] Error = ENOSYS (#38, Function not implemented): NotSupported
log01 :  1803.6410808563232
log02 :  1859.3192100524902
[2024-07-11T08:26:09.727Z][ERROR][T2][#25028][···Lseek][syscall] Error = ESPIPE (#29, Illegal seek): libc error [line = 240, file = src/fs/stdio.rs]
[2024-07-11T08:26:11.455Z][ERROR][T2][#33065][···Lseek][syscall] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
[2024-07-11T08:26:11.945Z][ERROR][T2][#33765][···Lseek][syscall] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
[2024-07-11T08:26:11.945Z][ERROR][T2][#33768][···Lseek][syscall] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
[2024-07-11T08:26:11.946Z][ERROR][T2][#33871][···Lseek][syscall] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
log03 :  20921.085119247437
log2 :  20921.932220458984
log3 :  20922.318935394287
log4 :  20922.391414642334
log5 :  21044.830322265625
log6 :  21045.197010040283
[2024-07-11T08:26:15.582Z][ERROR][T2][#51613][Getrandom][syscall] Error = EINVAL (#22, Invalid argument): invalid flags [line = 917, file = src/syscall/mod.rs]
[2024-07-11T08:26:15.583Z][ERROR][T2][#51621][Getrandom][syscall] Error = EFAULT (#14, Bad address): the whole buffer is not in the user space [line = 33, file = src/util/mem_util.rs]
[2024-07-11T08:26:15.583Z][ERROR][T2][#51624][···Statx][syscall] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 1046, file = src/syscall/mod.rs]
[2024-07-11T08:26:15.583Z][ERROR][T2][#51626][···Statx][syscall] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 1046, file = src/syscall/mod.rs]
[2024-07-11T08:26:15.583Z][ERROR][T2][#51627][·Fstatat][syscall] Error = EINVAL (#22, Invalid argument): NULL address is invalid [line = 48, file = src/util/mem_util.rs]
[2024-07-11T08:26:15.607Z][ERROR][T2][#51938][···Mkdir][syscall] Error = EEXIST (#17, File exists):  [line = 14, file = src/fs/file_ops/mkdir.rs]
[2024-07-11T08:26:15.627Z][ERROR][T2][#51979][···Lseek][syscall] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
[2024-07-11T08:26:15.628Z][ERROR][T2][#52085][···Lseek][syscall] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
[2024-07-11T08:26:15.630Z][ERROR][T2][#52191][···Lseek][syscall] Error = ENOSYS (#38, Function not implemented): occlum_libos_core_rs::fs::pipe::PipeReader does not support seek [line = 43, file = src/fs/file.rs]
Traceback (most recent call last):
  File "//ml.py", line 31, in <module>
    model.compile(X_train)
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/ml/sklearn/base.py", line 575, in compile
    self.fhe_circuit_ = module_to_compile.compile(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 606, in compile
    circuit = Circuit(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/circuit.py", line 67, in __init__
    self.enable_fhe_execution()
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/circuit.py", line 134, in enable_fhe_execution
    self.server = Server.create(
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/fhe/compilation/server.py", line 220, in create
    compilation_result = support.compile(mlir, options, compilation_context)
  File "/opt/python-occlum/lib/python3.10/site-packages/concrete/compiler/library_support.py", line 172, in compile
    self.cpp().compile(
RuntimeError: Can't emit artifacts: Cannot allocate memory
Cannot call the linker: ld --shared -o /tmp/tmpidomq_u7/sharedlib.so /tmp/tmpidomq_u7/program.module-0.mlir.o /opt/python-occlum/lib/python3.10/site-packages/concrete_python.libs/libConcretelangRuntime-32c53a6a.so -rpath=/opt/python-occlum/lib/python3.10/site-packages/concrete_python.libs --disable-new-dtags 2>&1
```

# Environment

- HW: SGX2
- OS:  Ubuntu20.04
- Occlum version: 0.29.5

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by qzheng527** [comment]
@thempp66 The hostfs mount makes the content in /tmp accessible by non-TEE users in plaintext. I think it is not a secure way.
Any spefical reason you want to do hostfs mount for /tmp? Usually, the /tmp is mounted either in SEFS (default) or in ramfs way like below.
{"target": "/tmp", "type": "ramfs"}

**Comment by thempp66** [comment]
Thanks for your help. After tried to mount it like `{"target": "/tmp", "type": "ramfs"}` I still got the same error `Cannot call the linker: ld --shared -o /tmp/tmpdwb9qqzj/sharedlib.so /tmp/tmpdwb9qqzj/program.module-0.mlir.o /opt/python-occlum/lib/python3.10/site-packages/concrete_python.libs/libConcretelangRuntime-32c53a6a.so -rpath=/opt/python-occlum/lib/python3.10/site-packages/concrete_python.libs --disable-new-dtags 2>&1`.

By the way, I need to mount `tmp` because this lib generates some file in `/tmp` and they will be used when runing.

**Comment by qzheng527** [comment]
@thempp66 check this part, looks some binary is not existed. Also in your case, you don't need mount /tmp which is in Occlum FS in default.
```
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52185][··Execve][process] execve: path: "/usr/local/bin/pip", argv: ["pip", "--disable-pip-version-check", "list"], envp: ["OCCLUM=yes", "PYTHONHOME=/opt/python-occlum", "OPENBLAS_NUM_THREADS=1", "USE_RTLD_GLOBAL_WITH_LIBTORCH=false", "USE_GLOBAL_DEPS=false", "PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "PYTHONHOME=/opt/python-occlum", "KMP_DUPLICATE_LIB_OK=True", "KMP_INIT_AT_FORK=FALSE", "USE_INPUT_COMPRESSION=1", "USE_KEY_COMPRESSION=1", "TREES_USE_ROUNDING=1"][0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52185][··Execve][fs] lookup_inode: cwd: "/", path: "/usr/local/bin/pip"[0m
[33m[2024-07-11T08:48:51.204Z][ WARN][T2][#52185][··Execve][syscall] Error = ENOENT (#2, No such file or directory): EntryNotFound[0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52186][··Execve][process] execve: path: "/usr/sbin/pip", argv: ["pip", "--disable-pip-version-check", "list"], envp: ["OCCLUM=yes", "PYTHONHOME=/opt/python-occlum", "OPENBLAS_NUM_THREADS=1", "USE_RTLD_GLOBAL_WITH_LIBTORCH=false", "USE_GLOBAL_DEPS=false", "PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "PYTHONHOME=/opt/python-occlum", "KMP_DUPLICATE_LIB_OK=True", "KMP_INIT_AT_FORK=FALSE", "USE_INPUT_COMPRESSION=1", "USE_KEY_COMPRESSION=1", "TREES_USE_ROUNDING=1"][0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52186][··Execve][fs] lookup_inode: cwd: "/", path: "/usr/sbin/pip"[0m
[33m[2024-07-11T08:48:51.204Z][ WARN][T2][#52186][··Execve][syscall] Error = ENOENT (#2, No such file or directory): EntryNotFound[0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52187][··Execve][process] execve: path: "/usr/bin/pip", argv: ["pip", "--disable-pip-version-check", "list"], envp: ["OCCLUM=yes", "PYTHONHOME=/opt/python-occlum", "OPENBLAS_NUM_THREADS=1", "USE_RTLD_GLOBAL_WITH_LIBTORCH=false", "USE_GLOBAL_DEPS=false", "PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "PYTHONHOME=/opt/python-occlum", "KMP_DUPLICATE_LIB_OK=True", "KMP_INIT_AT_FORK=FALSE", "USE_INPUT_COMPRESSION=1", "USE_KEY_COMPRESSION=1", "TREES_USE_ROUNDING=1"][0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52187][··Execve][fs] lookup_inode: cwd: "/", path: "/usr/bin/pip"[0m
[33m[2024-07-11T08:48:51.204Z][ WARN][T2][#52187][··Execve][syscall] Error = ENOENT (#2, No such file or directory): EntryNotFound[0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52188][··Execve][process] execve: path: "/sbin/pip", argv: ["pip", "--disable-pip-version-check", "list"], envp: ["OCCLUM=yes", "PYTHONHOME=/opt/python-occlum", "OPENBLAS_NUM_THREADS=1", "USE_RTLD_GLOBAL_WITH_LIBTORCH=false", "USE_GLOBAL_DEPS=false", "PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "PYTHONHOME=/opt/python-occlum", "KMP_DUPLICATE_LIB_OK=True", "KMP_INIT_AT_FORK=FALSE", "USE_INPUT_COMPRESSION=1", "USE_KEY_COMPRESSION=1", "TREES_USE_ROUNDING=1"][0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52188][··Execve][fs] lookup_inode: cwd: "/", path: "/sbin/pip"[0m
[33m[2024-07-11T08:48:51.204Z][ WARN][T2][#52188][··Execve][syscall] Error = ENOENT (#2, No such file or directory): EntryNotFound[0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52189][··Execve][process] execve: path: "/bin/pip", argv: ["pip", "--disable-pip-version-check", "list"], envp: ["OCCLUM=yes", "PYTHONHOME=/opt/python-occlum", "OPENBLAS_NUM_THREADS=1", "USE_RTLD_GLOBAL_WITH_LIBTORCH=false", "USE_GLOBAL_DEPS=false", "PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "PYTHONHOME=/opt/python-occlum", "KMP_DUPLICATE_LIB_OK=True", "KMP_INIT_AT_FORK=FALSE", "USE_INPUT_COMPRESSION=1", "USE_KEY_COMPRESSION=1", "TREES_USE_ROUNDING=1"][0m
[0m[2024-07-11T08:48:51.204Z][DEBUG][T2][#52189][··Execve][fs] lookup_inode: cwd: "/", path: "/bin/pip"[0m
[33m[2024-07-11T08:48:51.204Z][ WARN][T2][#52189][··Execve][syscall] Error = ENOENT (#2, No such file or directory): EntryNotFound[0m
```

**Comment by thempp66** [comment]
OK. I remove mounting `/tmp` and the PATH. The error you mentioned didn't exist. But it still dosen't work. I found some error in debug log, but I am not sure which one must to be solved. Looking forward to your reply. Thanks!

Here is the [log.zip](https://github.com/user-attachments/files/16346571/log.zip)
