### ISSUE TITLE
[BUG]Occlum process panicked at `make test`

### ISSUE THREAD

**Issue by liqinggd** [occlum/occlum#231]
# Describe the bug
When I run the `make test` after building Occlum in the Docker container, this may cause Occlum to panicked.
.
# To reproduce
1. run a Docker container provided by Occlum 
2. download the code from master(commit id : 4d4caa22656e6d5150807f95271ecb6253196041)
3. cd occlum && make && make test

# Expected behavior
make test pass

# Logs
```
RUN TEST => eventfd
  func test_fcntl_get_flags - [OK]
  func test_fcntl_set_flags - [OK]
  func test_create_with_flags - [OK]
  func test_read_write - [OK]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Embedded((EEXIST, "host fd has been registered")), location: Some(ErrorLocation { line: 53, file: "src/fs/host_fd.rs" }), cause: None }', src/fs/host_fd.rs:14:60
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1080
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::option::expect_none_failed
             at library/core/src/option.rs:1221
   8: occlum_libos_core_rs::fs::host_fd::HostFd::new
   9: occlum_libos_core_rs::fs::event_file::EventFile::new
  10: occlum_libos_core_rs::process::task::exec::exec
  11: occlum_libos_core_rs::entry::do_exec_thread
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/fs/host_fd.rs:27:14
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1080
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::option::expect_none_failed
             at library/core/src/option.rs:1221
   8: <occlum_libos_core_rs::fs::host_fd::HostFd as core::ops::drop::Drop>::drop
   9: core::ptr::drop_in_place
  10: alloc::sync::Arc<T>::drop_slow
  11: <hashbrown_tstd::raw::RawTable<T> as core::ops::drop::Drop>::drop
  12: core::ptr::drop_in_place
  13: alloc::sync::Arc<T>::drop_slow
  14: occlum_libos_core_rs::fs::file_ops::close::do_close
  15: occlum_libos_core_rs::syscall::dispatch_syscall
  16: occlum_libos_core_rs::syscall::do_syscall
  17: occlum_syscall
  18: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 3
```

# Environment

- HW: [Intel nuc] 
- OS: [Ubuntu18.04]
- Occlum version: [0.17.0]

# Additional context
No

# Possible solution/Implementation
epoll related bug?

**Comment by jessehui** [comment]
CI might also hit this bug. Logs are similar but not exactly the same. Please check out: https://github.com/occlum/occlum/runs/1417156987?check_suite_focus=true.
```
RUN TEST => server
  func test_read_write - [OK]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Embedded((EEXIST, "host fd has been registered")), location: Some(ErrorLocation { line: 53, file: "src/fs/host_fd.rs" }), cause: None }', src/fs/host_fd.rs:14:60
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1080
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::option::expect_none_failed
             at library/core/src/option.rs:1221
   8: occlum_libos_core_rs::fs::host_fd::HostFd::new
   9: occlum_libos_core_rs::net::syscalls::do_socket
  10: occlum_libos_core_rs::syscall::dispatch_syscall
  11: occlum_libos_core_rs::syscall::do_syscall
  12: occlum_syscall
  13: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 3
Error: The operation was canceled.
```

**Comment by tatetian** [comment]
Hi @liqinggd and @jessehui , thanks for reporting the bug. I think #236 should be able to fix this bug.

**Comment by guzongmin** [comment]
Close this bug, since
