### ISSUE TITLE
[BUG]Occlum crashed in sched UT

### ISSUE THREAD

**Issue by guzongmin** [occlum/occlum#389]
# Describe the bug
Occlum crashed in sched UT

# To reproduce
Occlum crashed in UT
https://github.com/occlum/occlum/pull/388/checks?check_run_id=2307152916 

# Expected behavior
UT success

# Logs
RUN TEST => sched
[2021-04-09T15:39:00.553Z][TRACE][T0][#0] env_checked from env untrusted: []
[2021-04-09T15:39:00.553Z][TRACE][T0][#0] env_merged = ["OCCLUM=yes", "STABLE=yes", "OVERRIDE=N"]  (default env and untrusted env)
[2021-04-09T15:39:00.553Z][DEBUG][T0][#0] lookup_inode: cwd: "/", path: "/bin/sched"
[2021-04-09T15:39:00.554Z][TRACE][T0][#0] PT_INTERP offset = 512, count = 25
[2021-04-09T15:39:00.554Z][TRACE][T0][#0] interpreter = Some("/lib/ld-musl-x86_64.so.1")
[2021-04-09T15:39:00.554Z][TRACE][T0][#0] ldso_path = "/lib/ld-musl-x86_64.so.1"
[2021-04-09T15:39:00.554Z][DEBUG][T0][#0] lookup_inode: cwd: "/", path: "/lib/ld-musl-x86_64.so.1"
[2021-04-09T15:39:00.555Z][TRACE][T0][#0] interpreter = None
[2021-04-09T15:39:00.555Z][DEBUG][T0][#0] allocated rsrv addr is 0x7f2887840000, len is 0x7c96000
[2021-04-09T15:39:00.555Z][TRACE][T0][#0] entrophy size = 16329728
[2021-04-09T15:39:00.558Z][TRACE][T0][#0] elf range = VMRange { start: 0x7f2887e00000, end: 0x7f2888205000, size: 0x405000 }
[2021-04-09T15:39:00.562Z][TRACE][T0][#0] elf range = VMRange { start: 0x7f2888400000, end: 0x7f2888896000, size: 0x496000 }
[2021-04-09T15:39:00.562Z][TRACE][T0][#0] entrophy size = 1048576
[2021-04-09T15:39:00.563Z][TRACE][T0][#0] heap range = VMRange { start: 0x7f28888fa000, end: 0x7f28890fa000, size: 0x800000 }
[2021-04-09T15:39:00.563Z][TRACE][T0][#0] entrophy size = 1048576
[2021-04-09T15:39:00.563Z][TRACE][T0][#0] stack range = VMRange { start: 0x7f2889132000, end: 0x7f2889532000, size: 0x400000 }
[2021-04-09T15:39:00.563Z][ INFO][T0][#0] Process created: elf = /bin/sched, pid = 13
[2021-04-09T15:39:00.563Z][TRACE][T13][#1][ArchPrctl] Syscall { num = ArchPrctl, code = 4098, addr = 0x7f2888694d88 }
[2021-04-09T15:39:00.563Z][DEBUG][T13][#1][ArchPrctl] do_arch_prctl: code: ARCH_SET_FS, addr: 0x7f2888694d88
[2021-04-09T15:39:00.563Z][TRACE][T13][#1][ArchPrctl] Retval = 0
[2021-04-09T15:39:00.563Z][TRACE][T13][#2][SetTidAddress] Syscall { num = SetTidAddress, tidptr = 0x7f2888695364 }
[2021-04-09T15:39:00.563Z][DEBUG][T13][#2][SetTidAddress] set_tid_address: tidptr: 0x7f2888695364
[2021-04-09T15:39:00.563Z][TRACE][T13][#2][SetTidAddress] Retval = 13
[2021-04-09T15:39:00.563Z][TRACE][T13][#3][Mprotect] Syscall { num = Mprotect, addr = 139812064006144, len = 4096, prot = 1 }
[2021-04-09T15:39:00.564Z][DEBUG][T13][#3][Mprotect] mprotect: addr: 0x7f2888691000, size: 0x1000, perms: READ
[2021-04-09T15:39:00.564Z][TRACE][T13][#3][Mprotect] Retval = 0
[2021-04-09T15:39:00.564Z][TRACE][T13][#4][Mprotect] Syscall { num = Mprotect, addr = 139812057133056, len = 4096, prot = 1 }
[2021-04-09T15:39:00.564Z][DEBUG][T13][#4][Mprotect] mprotect: addr: 0x7f2888003000, size: 0x1000, perms: READ
[2021-04-09T15:39:00.564Z][TRACE][T13][#4][Mprotect] Retval = 0
[2021-04-09T15:39:00.564Z][TRACE][T13][#5][SchedGetaffinity] Syscall { num = SchedGetaffinity, pid = 0, cpusize = 128, buf = 0x7f2889531c20 }
[2021-04-09T15:39:00.564Z][DEBUG][T13][#5][SchedGetaffinity] do_sched_getaffinity tid: 0
[2021-04-09T15:39:00.573Z][TRACE][T14][#6][··Getpid] Syscall { num = Getpid }
[2021-04-09T15:39:00.573Z][TRACE][T14][#6][··Getpid] Retval = 14
[2021-04-09T15:39:00.573Z][TRACE][T14][#7][···Ioctl] Syscall { num = Ioctl, fd = 1, cmd = 21523, argp = 0x7f2891209af8 }
[2021-04-09T15:39:00.573Z][DEBUG][T14][#7][···Ioctl] ioctl: fd: 1, cmd: TIOCGWINSZ(WinSize { ws_row: 33992, ws_col: 36867, ws_xpixel: 32552, ws_ypixel: 0 })
Error: 021-04-09T15:39:00.573Z][ERROR][T14][#7][···Ioctl] Error = ENOTTY (#25, Not a typewriter): libc error [line = 186, file = src/fs/stdio.rs]
[2021-04-09T15:39:00.573Z][TRACE][T14][#7][···Ioctl] Retval = -25
[2021-04-09T15:39:00.573Z][TRACE][T14][#8][··Writev] Syscall { num = Writev, fd = 1, iov = 0x7f2891209aa0, count = 2 }
[2021-04-09T15:39:00.573Z][DEBUG][T14][#8][··Writev] writev: fd: 1
[2021-04-09T15:39:00.573Z][TRACE][T14][#8][··Writev] Retval = 46
[2021-04-09T15:39:00.573Z][TRACE][T14][#9][ExitGroup] Syscall { num = ExitGroup, exit_status = 0 }
[2021-04-09T15:39:00.573Z][DEBUG][T14][#9][ExitGroup] exit_group: 0
[2021-04-09T15:39:00.573Z][DEBUG][T14][#9][ExitGroup] futex_wake_bitset addr: 0x7f2890295364, max_count: 1, bitset: 0xffffffff
[2021-04-09T15:39:00.573Z][TRACE][T14][#9][ExitGroup] Retval = 0
[2021-04-09T15:39:00.573Z][ INFO][T14][#9][ExitGroup] Thread exited: tid = 14, status = 0
[2021-04-09T15:39:00.573Z][ WARN][T0][#9][ExitGroup] HostFS: sync is unimplemented
thread '<unnamed>' panicked at 'range end index 139811991875081 out of range for slice of length 66', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.17.4/src/slice/traits.rs:362:1
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1080
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::slice::slice_end_index_len_fail
             at library/core/src/slice/mod.rs:3306
   8: bitvec::slice::traits::<impl core::fmt::Binary for bitvec::slice::BitSlice<O,T>>::fmt::{{closure}}
   9: bitvec::slice::traits::<impl core::fmt::Display for bitvec::slice::BitSlice<O,T>>::fmt
  10: core::fmt::builders::DebugStruct::field::{{closure}}
             at library/core/src/fmt/builders.rs:154
  11: core::result::Result<T,E>::and_then
             at library/core/src/result.rs:708
  12: core::fmt::builders::DebugStruct::field
             at library/core/src/fmt/builders.rs:137
  13: <&T as core::fmt::Debug>::fmt
  14: core::fmt::write
             at library/core/src/fmt/mod.rs:1080
  15: <core::fmt::Arguments as core::fmt::Display>::fmt
             at library/core/src/fmt/mod.rs:451
  16: <core::fmt::Arguments as core::fmt::Debug>::fmt
             at library/core/src/fmt/mod.rs:444
  17: core::fmt::run
             at library/core/src/fmt/mod.rs:1114
  18: core::fmt::write
             at library/core/src/fmt/mod.rs:1089
  19: core::fmt::Write::write_fmt
             at /rustc/0e2c1281e909ca38479b97962fc9248f75d66412/library/core/src/fmt/mod.rs:186
  20: alloc::fmt::format
             at library/alloc/src/fmt.rs:577
  21: <occlum_libos_core_rs::util::log::SimpleLogger as log::Log>::log
  22: log::__private_api_log
  23: occlum_libos_core_rs::sched::do_sched_affinity::do_sched_setaffinity
  24: occlum_libos_core_rs::sched::syscalls::do_sched_setaffinity
  25: occlum_libos_core_rs::syscall::dispatch_syscall
  26: occlum_libos_core_rs::syscall::do_syscall
  27: occlum_syscall
  28: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Error: The operation was canceled.

# Environment

- HW: SIM mode
- OS: [e.g. Ubuntu18.04, CentOS8.2]
- Occlum version: [e.g. 0.21.0]

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by guzongmin** [comment]
Can not reproduce this issue anymore.
