### ISSUE TITLE
Support Python Multiprocess

### ISSUE THREAD

**Issue by jessehui** [occlum/occlum#413]
- [ ] Add support for posix spawn attribute for set signal mask and signal action (SIG_DFL or SIG_IGN)
- [ ] Support ioctl TCGETS
- [ ] Support statfs syscall
- [ ] Support wait NOHANG
- [ ] Support more detailed log info for read/write pipe/socket

There is also a known issue that python multiprocess running in Occlum(based on 0.21.0) will cause competition for pipe readers and hang. It may be a hidden bug of python but not sure.

**Comment by tinyAdapter** [comment]
Hi, I wonder if the error
```py
Traceback (most recent call last):
...
  File "/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 38] Function not implemented
```
when calling `subprocess.Popen` is due to the limitations listed here.

**Comment by guzongmin** [comment]
Would you please show the Occlum trace?

**Comment by tinyAdapter** [comment]
[occlum_popen_test_trace.log](https://github.com/occlum/occlum/files/6566303/occlum_popen_test_trace.log)

It can be reproduced by the following script:
```py
root@581b1e9b6489:~/demos/python/occlum_instance# cat image/popen_test.py
import subprocess
import sys


p = subprocess.Popen('date', stdout=sys.stdout, stderr=sys.stderr)
p.communicate()
```

**Comment by jessehui** [comment]
@tinyAdapter I am not sure which Python version you are using. The thing is to run multiprocess with Python, fork will be called and we don't have plans to support that. So to support multiprocess with Python, we will change Python implementation to use `posix_spawn`. We have started the work on Python 3.10 but it is not mature.

To answer your question, based on the log you provided, it looks like the reason is lacking the support of FIOCLEX for ioctl, which is a known issue but not listed here.

**Comment by tinyAdapter** [comment]
I followed the guide the build Occlum Docker image https://github.com/occlum/occlum/tree/master/tools/docker, and the guide to run Python demo https://github.com/occlum/occlum/tree/master/demos/python. Although because of some dependency issues, I changed from alpine 3.10 to alpine 3.12. The Python is still version 3.7. So the image I pulled is `python:3.7-alpine3.12`.

The demo passed, and when I tried to build and run my own project inside the container which includes multiprocessing, this error occurred.

Anyway, thanks for your reply :)

**Comment by jessehui** [comment]
@tinyAdapter Sorry but current Python demo doesn't support multiprocess usage.

**Comment by jessehui** [comment]
@tinyAdapter May I know what application you are trying to run with Occlum and Python multiprocess? If possible, you can provide us a demo so that we can use it to test before releasing this feature.

**Comment by tinyAdapter** [comment]
@jessehui Sorry but it is a private commercial application so I cannot provide any information about it :(

**Comment by guolanting** [comment]
@jessehui "The thing is to run multiprocess with Python, fork will be called and we don't have plans to support that." fork is used by many libraries. why occlum do not support fork?  Why don't support fork and spawn at the same time?

**Comment by guzongmin** [comment]
fork requires the OS to manager the memory mapping, SGX is not able to support it.
