### ISSUE TITLE
Failed to establish a new HTTPS connection in occlum

### ISSUE THREAD

**Issue by Lili0820** [occlum/occlum#420]
When I tried to access a web api with Python, there is a connection error.  I exclude network issues, and I don't know the reason.

**Comment by guzongmin** [comment]
@Lili0820 Can you please show me a simple case to help reproduce the issue?

**Comment by Lili0820** [comment]
The python script is as follows:
```
import requests


def get_web_api_json_result(url, params):
    ret = requests.get(url, params=params)
    if ret.status_code == 200:
        result = ret.text.replace(" ", "")
        result = result.replace("\n", "")
        return result


url = "https://samples.openweathermap.org/data/2.5/weather"
param = {"q": "London,uk", "appid": "b6907d289e10d714a6e88b30761fae22"}
print(get_web_api_json_result(url, param))
```

The error message is:
```
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='samples.openweathermap.org', port=443): Max retries exceeded with url: /data/2.5/weather?q=London%2Cuk&appid=b6907d289e10d714a6e88b30761fae22 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f92da6f7f60>: Failed to establish a new connection: [Errno -3] Try again',))
```

**Comment by guzongmin** [comment]
@Lili0820 Can you please share the deployment script? This python script is not able to run in the demo python environment by default. These are some python depends on modules missed. I need to know them and copy them into occlum environment.

**Comment by Lili0820** [comment]
```
# 2. Copy files into Occlum Workspace and build
if [ ! -d "image/lib/python3.6" ];then
    cp -f $alpine_fs/usr/local/bin/python3.6 image/bin
    cp -f $alpine_fs/usr/local/lib/libpython3.6m.so.1.0 image/lib
    cp -f $alpine_fs/usr/local/lib/libpython3.so image/lib
    cp -rf $alpine_fs/usr/local/lib/python3.6 image/lib
    cp -f $alpine_fs/usr/lib/libblas.so.3 image/lib
    cp -f $alpine_fs/usr/lib/libcblas.so.3 image/lib
    cp -f $alpine_fs/usr/lib/libbz2.so.1 image/lib
    cp -f $alpine_fs/usr/lib/libffi.so.6 image/lib
    cp -f $alpine_fs/usr/lib/libgcc_s.so.1 image/lib
    cp -f $alpine_fs/usr/lib/libgfortran.so.5 image/lib
    cp -f $alpine_fs/usr/lib/liblapack.so.3 image/lib
    cp -f $alpine_fs/usr/lib/liblzma.so.5 image/lib
    cp -f $alpine_fs/usr/lib/libquadmath.so.0 image/lib
    cp -f $alpine_fs/usr/lib/libssl.so.1.1 image/lib
    cp -f /lib64/ld-linux-x86-64.so.2 image/lib
    cp -f $alpine_fs/lib/libz.so.1 image/lib
    cp -f $alpine_fs/usr/lib/libexpat.so.1 image/lib
    cp -f $alpine_fs/usr/lib/libcrypto.so.1.1 image/lib
    cp -rf ../demo/ image
    new_json="$(jq '.resource_limits.user_space_size = "320MB" |
                    .resource_limits.kernel_space_heap_size = "256MB" |
                    .process.default_mmap_size = "256MB"' Occlum.json)" && \
    echo "${new_json}" > Occlum.json
    occlum build
fi
```

**Comment by Lili0820** [comment]
The python dependency is the `requests` module.

**Comment by jessehui** [comment]
@Lili0820 I reproduced this error with python3.7 also. And copy the `/etc/resolv.conf` of host to `occlum_instance/image/etc/ ` solves this.

**Comment by Lili0820** [comment]
OK. It works. Thanks~
