### ISSUE TITLE
[BUG][Simulation]Unexpected exception in CI

### ISSUE THREAD

**Issue by guzongmin** [occlum/occlum#455]
# Describe the bug
The daily CI crashed. The log shows it should be an unexpected exception issue.

# Logs
2021-06-01T13:18:16.0725455Z [0m[2021-06-01T13:18:16.067Z][TRACE][T38][#36][··Accept] Retval = 4[0m
2021-06-01T13:18:16.0726190Z [0m[2021-06-01T13:18:16.067Z][TRACE][T38][#37][···Close] Syscall { num = Close, fd = 3 }[0m
2021-06-01T13:18:16.0726929Z [0m[2021-06-01T13:18:16.067Z][DEBUG][T38][#37][···Close] close: fd: 3[0m
2021-06-01T13:18:16.0727614Z [0m[2021-06-01T13:18:16.067Z][TRACE][T38][#37][···Close] Retval = 0[0m
2021-06-01T13:18:16.0728457Z [0m[2021-06-01T13:18:16.067Z][TRACE][T38][#38][···Write] Syscall { num = Write, fd = 4, buf = 0x7fc8bbc021b7, size = 26 }[0m
2021-06-01T13:18:16.0729272Z [0m[2021-06-01T13:18:16.067Z][DEBUG][T38][#38][···Write] write: fd: 4[0m
2021-06-01T13:18:16.0729952Z [0m[2021-06-01T13:18:16.067Z][TRACE][T38][#38][···Write] Retval = 26[0m
2021-06-01T13:18:16.0730805Z [0m[2021-06-01T13:18:16.067Z][TRACE][T38][#39][····Read] Syscall { num = Read, fd = 4, buf = 0x7fc8bd2f2d50, size = 4 }[0m
2021-06-01T13:18:16.0731718Z [0m[2021-06-01T13:18:16.067Z][DEBUG][T38][#39][····Read] read: fd: 4[0m
2021-06-01T13:18:16.0732402Z [0m[2021-06-01T13:18:16.067Z][TRACE][T39][#33][····Read] Retval = 26[0m
2021-06-01T13:18:16.0733250Z [0m[2021-06-01T13:18:16.067Z][TRACE][T39][#34][···Write] Syscall { num = Write, fd = 4, buf = 0x7fc8c3801185, size = 4 }[0m
2021-06-01T13:18:16.0734035Z [0m[2021-06-01T13:18:16.067Z][DEBUG][T39][#34][···Write] write: fd: 4[0m
2021-06-01T13:18:16.0734723Z [0m[2021-06-01T13:18:16.067Z][TRACE][T39][#34][···Write] Retval = 4[0m
2021-06-01T13:18:16.0735456Z [0m[2021-06-01T13:18:16.067Z][TRACE][T39][#35][···Close] Syscall { num = Close, fd = 4 }[0m
2021-06-01T13:18:16.0736184Z [0m[2021-06-01T13:18:16.067Z][DEBUG][T39][#35][···Close] close: fd: 4[0m
2021-06-01T13:18:16.0736876Z [0m[2021-06-01T13:18:16.067Z][TRACE][T39][#35][···Close] Retval = 0[0m
2021-06-01T13:18:16.0737699Z [0m[2021-06-01T13:18:16.067Z][TRACE][T39][#36][ExitGroup] Syscall { num = ExitGroup, exit_status = 0 }[0m
2021-06-01T13:18:16.0738536Z [0m[2021-06-01T13:18:16.067Z][DEBUG][T39][#36][ExitGroup] exit_group: 0[0m
2021-06-01T13:18:16.0739252Z [0m[2021-06-01T13:18:16.067Z][TRACE][T39][#36][ExitGroup] Retval = 0[0m
2021-06-01T13:18:16.0740050Z [32m[2021-06-01T13:18:16.068Z][ INFO][T39][#36][ExitGroup] Thread exited: tid = 39, status = 0[0m
2021-06-01T13:18:16.0741019Z [33m[2021-06-01T13:18:16.068Z][ WARN][T0][#36][ExitGroup] HostFS: sync is unimplemented[0m
2021-06-01T13:18:16.0741823Z [0m[2021-06-01T13:18:16.068Z][TRACE][T38][#39][····Read] Retval = 4[0m
2021-06-01T13:18:16.0743027Z [0m[2021-06-01T13:18:16.068Z][TRACE][T38][#40][HandleException] Syscall { num = HandleException, info = 0x7fc8b869ebc0, fpregs = 0x7fc8b869e960, context = 0xefdd75a0fd5860f7 }[0m
2021-06-01T13:18:16.0745014Z [31m[2021-06-01T13:18:16.068Z][ERROR][T38][#40][HandleException] Error = EINVAL (#22, Invalid argument): Can only handle hardware / simulated exceptions [line = 107, file = src/exception/mod.rs][0m
2021-06-01T13:18:16.0746203Z [0m[2021-06-01T13:18:16.068Z][TRACE][T38][#40][HandleException] Retval = -22[0m
2021-06-01T13:18:16.0747176Z thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/exception/mod.rs:38:5
2021-06-01T13:18:16.0747847Z stack backtrace:
2021-06-01T13:18:16.0748774Z    0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
2021-06-01T13:18:16.0850898Z    1: core::fmt::write
2021-06-01T13:18:16.0851890Z              at library/core/src/fmt/mod.rs:1080
2021-06-01T13:18:16.0852837Z    2: sgx_tstd::io::Write::write_fmt
2021-06-01T13:18:16.0853447Z    3: sgx_tstd::panicking::default_panic_handler
2021-06-01T13:18:16.0854018Z    4: sgx_tstd::panicking::rust_panic_with_hook
2021-06-01T13:18:16.0854593Z    5: sgx_tstd::panicking::begin_panic
2021-06-01T13:18:16.0855253Z    6: handle_exception
2021-06-01T13:18:16.0856659Z note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
2021-06-01T13:18:16.0857518Z fatal runtime error: failed to initiate panic, error 3
2021-06-01T15:31:25.8870996Z ##[error]The operation was canceled.
2021-06-01T15:31:25.8896218Z Cleaning up orphan processes
2021-06-01T15:31:25.9127299Z Terminate orphan process: pid (22341) (docker)

# Environment

- SW
- OS: Ubuntu18.04
- Occlum version: 0.22.0

# Possible solution/Implementation
Need to confirm how to update the SGX_EXCEPTION_SIMULATED flag.

**Comment by guzongmin** [comment]
Could not reproduce. Close it.
