### ISSUE TITLE
[BUG]Crash in unix_socket UT

### ISSUE THREAD

**Issue by guzongmin** [occlum/occlum#465]
# Describe the bug
The unix_socket UT crashed

# Logs
RUN TEST => unix_socket
[2021-06-08T13:49:01.818Z][TRACE][T0][#0] env_checked from env untrusted: []
[2021-06-08T13:49:01.818Z][TRACE][T0][#0] env_merged = ["OCCLUM=yes", "STABLE=yes", "OVERRIDE=N"]  (default env and untrusted env)
[2021-06-08T13:49:01.818Z][DEBUG][T0][#0] lookup_inode: cwd: "/", path: "/bin/unix_socket"
[2021-06-08T13:49:01.819Z][TRACE][T0][#0] PT_INTERP offset = 512, count = 25
[2021-06-08T13:49:01.819Z][TRACE][T0][#0] interpreter = Some("/lib/ld-musl-x86_64.so.1")
[2021-06-08T13:49:01.819Z][TRACE][T0][#0] ldso_path = "/lib/ld-musl-x86_64.so.1"
[2021-06-08T13:49:01.819Z][DEBUG][T0][#0] lookup_inode: cwd: "/", path: "/lib/ld-musl-x86_64.so.1"
[2021-06-08T13:49:01.819Z][TRACE][T0][#0] interpreter = None
[2021-06-08T13:49:01.819Z][DEBUG][T0][#0] allocated rsrv addr is 0x7fee2384d000, len is 0x7c96000
[2021-06-08T13:49:01.819Z][TRACE][T0][#0] entrophy size = 16329728
[2021-06-08T13:49:01.822Z][TRACE][T0][#0] elf range = VMRange { start: 0x7fee24800000, end: 0x7fee24c04000, size: 0x404000 }
[2021-06-08T13:49:01.827Z][TRACE][T0][#0] elf range = VMRange { start: 0x7fee24e00000, end: 0x7fee25296000, size: 0x496000 }
[2021-06-08T13:49:01.827Z][TRACE][T0][#0] entrophy size = 1048576
[2021-06-08T13:49:01.827Z][TRACE][T0][#0] heap range = VMRange { start: 0x7fee25395000, end: 0x7fee25b95000, size: 0x800000 }
[2021-06-08T13:49:01.827Z][TRACE][T0][#0] entrophy size = 1048576
[2021-06-08T13:49:01.827Z][TRACE][T0][#0] stack range = VMRange { start: 0x7fee25c1c000, end: 0x7fee2601c000, size: 0x400000 }
[2021-06-08T13:49:01.827Z][TRACE][T0][#0] new process sigmask = SigSet { [] }
[2021-06-08T13:49:01.827Z][TRACE][T0][#0] new process sig_dispositions = SigDispositions (only none-default is shown) {}
[2021-06-08T13:49:01.827Z][ INFO][T0][#0] Process created: elf = /bin/unix_socket, pid = 49
[2021-06-08T13:49:01.828Z][TRACE][T49][#1][ArchPrctl] Syscall { num = ArchPrctl, code = 4098, addr = 0x7fee25094d88 }
[2021-06-08T13:49:01.828Z][DEBUG][T49][#1][ArchPrctl] do_arch_prctl: code: ARCH_SET_FS, addr: 0x7fee25094d88
[2021-06-08T13:49:01.828Z][TRACE][T49][#1][ArchPrctl] Retval = 0
[2021-06-08T13:49:01.828Z][TRACE][T49][#2][SetTidAddress] Syscall { num = SetTidAddress, tidptr = 0x7fee25095364 }
[2021-06-08T13:49:01.828Z][DEBUG][T49][#2][SetTidAddress] set_tid_address: tidptr: 0x7fee25095364
[2021-06-08T13:49:01.828Z][TRACE][T49][#2][SetTidAddress] Retval = 49
[2021-06-08T13:49:01.828Z][TRACE][T49][#3][Mprotect] Syscall { num = Mprotect, addr = 140660800294912, len = 4096, prot = 1 }
[2021-06-08T13:49:01.829Z][DEBUG][T49][#3][Mprotect] mprotect: addr: 0x7fee25091000, size: 0x1000, perms: READ
[2021-06-08T13:49:01.829Z][TRACE][T49][#3][Mprotect] Retval = 0
[2021-06-08T13:49:01.829Z][TRACE][T49][#4][Mprotect] Syscall { num = Mprotect, addr = 140660793417728, len = 4096, prot = 1 }
[2021-06-08T13:49:01.829Z][DEBUG][T49][#4][Mprotect] mprotect: addr: 0x7fee24a02000, size: 0x1000, perms: READ
[2021-06-08T13:49:01.829Z][TRACE][T49][#4][Mprotect] Retval = 0
[2021-06-08T13:49:01.829Z][TRACE][T49][#5][Socketpair] Syscall { num = Socketpair, domain = 1, socket_type = 1, protocol = 0, sv = 0x7fee2601be28 }
[2021-06-08T13:49:01.829Z][DEBUG][T49][#5][Socketpair] socketpair: (3, 4)
[2021-06-08T13:49:01.829Z][TRACE][T49][#5][Socketpair] Retval = 0
[2021-06-08T13:49:01.829Z][TRACE][T49][#6][SpawnMusl] Syscall { num = SpawnMusl, child_pid_ptr = 0x7fee2601bd50, path = 0x7fee24802029, argv = 0x7fee2601bd60, envp = 0x0, fdop_list = 0x7fee250953a0, attribute_list = 0x0 }
[2021-06-08T13:49:01.841Z][TRACE][T0][#8][····Read] Retval = -14
[2021-06-08T13:49:01.841Z][TRACE][T0][#9][···Ioctl] Syscall { num = Ioctl, fd = 1, cmd = 21523, argp = 0x7fee2601b9a8 }
Error: 021-06-08T13:49:01.841Z][ERROR][T0][#9][···Ioctl] Error = EFAULT (#14, Bad address): pointer is not in the user space [line = 15, file = src/util/mem_util.rs]
[2021-06-08T13:49:01.841Z][TRACE][T0][#9][···Ioctl] Retval = -14
[2021-06-08T13:49:01.842Z][TRACE][T0][#10][··Writev] Syscall { num = Writev, fd = 1, iov = 0x7fee2601b950, count = 2 }
Error: 021-06-08T13:49:01.842Z][ERROR][T0][#10][··Writev] Error = EFAULT (#14, Bad address): the whole buffer is not in the user space [line = 33, file = src/util/mem_util.rs]
[2021-06-08T13:49:01.842Z][TRACE][T0][#10][··Writev] Retval = -14
[2021-06-08T13:49:01.842Z][TRACE][T0][#11][···Close] Syscall { num = Close, fd = 3 }
[2021-06-08T13:49:01.842Z][DEBUG][T0][#11][···Close] close: fd: 3
Error: 021-06-08T13:49:01.842Z][ERROR][T0][#11][···Close] Error = EBADF (#9, Bad file number): Invalid file descriptor [line = 128, file = src/fs/file_table.rs]
[2021-06-08T13:49:01.842Z][TRACE][T0][#11][···Close] Retval = -9
[2021-06-08T13:49:01.842Z][TRACE][T0][#12][···Close] Syscall { num = Close, fd = 4 }
[2021-06-08T13:49:01.842Z][DEBUG][T0][#12][···Close] close: fd: 4
Error: 021-06-08T13:49:01.842Z][ERROR][T0][#12][···Close] Error = EBADF (#9, Bad file number): Invalid file descriptor [line = 128, file = src/fs/file_table.rs]
[2021-06-08T13:49:01.842Z][TRACE][T0][#12][···Close] Retval = -9
[2021-06-08T13:49:01.842Z][TRACE][T0][#13][··Writev] Syscall { num = Writev, fd = 1, iov = 0x7fee2601bdd0, count = 2 }
Error: 021-06-08T13:49:01.842Z][ERROR][T0][#13][··Writev] Error = EFAULT (#14, Bad address): the whole buffer is not in the user space [line = 33, file = src/util/mem_util.rs]
[2021-06-08T13:49:01.842Z][TRACE][T0][#13][··Writev] Retval = -14
[2021-06-08T13:49:01.842Z][TRACE][T0][#14][ExitGroup] Syscall { num = ExitGroup, exit_status = -1 }
[2021-06-08T13:49:01.842Z][DEBUG][T0][#14][ExitGroup] exit_group: -1
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/process/thread/mod.rs:194:14
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1076
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::panicking::panic
             at library/core/src/panicking.rs:50
   8: occlum_libos_core_rs::process::thread::Thread::exit
   9: occlum_libos_core_rs::process::do_exit::exit_thread
  10: occlum_libos_core_rs::process::do_exit::do_exit_group
  11: occlum_libos_core_rs::syscall::dispatch_syscall
  12: occlum_libos_core_rs::syscall::do_syscall
  13: occlum_syscall
  14: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5

# Environment

- HW: simulation
- OS: Ubuntu18.04
- Occlum version: 0.22.0

**Comment by guzongmin** [comment]
[2021-06-08T13:49:01.838Z][DEBUG][T49][#7][····Poll] poll: poll_fds: [PollFd { fd: 4, events: IN | ERR | HUP, revents: Cell { value: (empty) } }], timeout: None
[2021-06-08T13:49:01.840Z][TRACE][T0][#7][····Poll] Retval = 1

The two lines should be the same syscall, but the process ID changed. It should be the root cause.

**Comment by tatetian** [comment]
I haven't got the time to dive into the problem, but I am surprised that the panic happens when manipulating `THREAD_NOTIFIERS`, which is part of the already deprecated event notification mechanism. In NGO, all usage of `THREAD_NOTIFIERS` and related code are completed removed. Even in the upstream Occlum, I don't think `THREAD_NOTIFIERS` is useful at more. Try simply removed all usage of `THREAD_NOTIFIERS`. I guess everything should work fine.
