### ISSUE TITLE
How to create file into an empty directory which is mounted with "MAC" parameter?

### ISSUE THREAD

**Issue by asdfsx** [occlum/occlum#504]
I create a sefs filesystem using command 
```
sefs-cli_sim \
  --enclave /opt/occlum/build/lib/libsefs-cli.signed.so \
  zip \
  sefs/sefs \
  sefs/mount \
  sefs/.SEFS_MAC
```
The `sefs/sefs` is an empty direction.

Then I mount the `sefs/mount` use following config, and the `/sefs` should be an empty directory.
```
{
      "target": "/sefs",
      "type": "sefs",
      "source": "./sefs/mount",
      "options": {
        "MAC": "7c-56-03-17-38-76-78-fe-5d-69-d1-20-b3-46-80-e6"
      }
},
```

Then I execute a python script
```
import sqlite3 

DB_FILE = "/sefs/test123.db"

print("create table")
conn = sqlite3.connect(DB_FILE)
c = conn.cursor()
c.execute('''CREATE TABLE COMPANY
           (ID INT PRIMARY KEY     NOT NULL,
            NAME           TEXT    NOT NULL,
            AGE            INT     NOT NULL,
            ADDRESS        CHAR(50),
            SALARY         REAL);''')
conn.commit()
conn.close()
```

And got the following errors
```
# occlum run /bin/python3 sqlite.py
create table
thread '<unnamed>' panicked at 'FsError::NoIntegrity', /root/occlum/deps/sefs/rcore-fs-sefs/src/lib.rs:194:13
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1076
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::panicking::panic
             at library/core/src/panicking.rs:50
   8: rcore_fs_sefs::SEFS::_new_inode
   9: rcore_fs_sefs::SEFS::get_inode
  10: <rcore_fs_sefs::SEFS as rcore_fs::vfs::FileSystem>::root_inode
  11: rcore_fs_mountfs::MountFS::root_inode
  12: rcore_fs_mountfs::MNode::overlaid_inode
  13: rcore_fs_mountfs::MNode::find
  14: <rcore_fs_mountfs::MNode as rcore_fs::vfs::INode>::find
  15: rcore_fs::vfs::INode::lookup_follow
  16: occlum_libos_core_rs::fs::fs_view::FsView::lookup_inode
  17: occlum_libos_core_rs::fs::file_ops::stat::do_fstatat
  18: occlum_libos_core_rs::fs::syscalls::do_fstatat
  19: occlum_libos_core_rs::syscall::dispatch_syscall
  20: occlum_libos_core_rs::syscall::do_syscall
  21: occlum_syscall
  22: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum: line 318:  4598 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```

If I execute the script again, I got the following error
```
# occlum run /bin/python3 sqlite.py
Error: Os { code: 5, kind: Other, message: "I/O error" }
[ERROR] occlum-pal: The init process exit with code: 1 (line 58, file src/pal_api.c)
[ERROR] occlum-pal: Failed to run the init process: EINVAL (line 125, file src/pal_api.c)
[ERROR] occlum-pal: Failed to do ECall: occlum_ecall_broadcast_interrupts with error code 0x2002: Invalid enclave identification. (line 27, file src/pal_interrupt_thread.c)
```

My question is can I write sth into sefs filesystem, which is created by `sefs-cli_sim`, or it's only readable.

Further more, what's the difference between SEFS with `temporary` config and SEFS with `MAC` config

@liqinggd

**Comment by guzongmin** [comment]
@asdfsx Seems that you do not want to use the default SEFS. Can you please introduce your motivation? Then we are able to support your requirement better.

**Comment by liqinggd** [comment]
Hi, the image is integrity-only protected, so it cannot be modified(read-only). If you want to use an empty folder to write something, just mount an empty dir as the sefs.

SEFS with `temporary` option is a temporary fs. On every bootup, the content will be cleared.

**Comment by asdfsx** [comment]
@guzongmin I'm doing some research work. I just want to persistence some data into SEFS, and these data should not be clear every time.

So SEFS with MAC option is read-only. SEFS with `temporary:true`, the content will be cleared when execute `occlum run`.
Am I right @liqinggd ?
What about `temporary:false`?

**Comment by liqinggd** [comment]
@asdfsx Correct, `temporary=false` is the default value for the configuration of SEFS.

**Comment by asdfsx** [comment]
Thx @liqinggd @guzongmin 
Time  to learn Rust
