### ISSUE TITLE
[BUG]about sqlite golang demo

### ISSUE THREAD

**Issue by james-ray** [occlum/occlum#756]
# Describe the bug

# To reproduce
1.  I made some modification to go_sqlite/simple_demo.go
```
func main() {
        previousTime := time.Now()
        fmt.Printf("Starting the Golang SQLite demo: at %s\n", previousTime.Format("2006-01-02T15:04:05.999999999Z07:00"))

        dbSourceName := "golang_sql_driver.db"
        //os.Remove(dbSourceName)

        dbDriverName := "sqlite3"
        db, err := sql.Open(dbDriverName, dbSourceName)
        if err != nil {
                fmt.Println("Failed to open the database:", err)
        }
        defer db.Close()

        if err = db.Ping(); err != nil {
                fmt.Println("Failed to establish a connection to the database:", err)
        }

        if len(os.Args)==2{
                fmt.Println("write table")
        tx, err := db.Begin()
        if err != nil {
                fmt.Println("Failed to start a database transaction:", err)
        }

        sqlStatement := `
        create table if not exists SqlDrivers (dbName varchar(255), pkgLink varchar(255), testSuite varchar(255));
        delete from SqlDrivers;
        `
        _, err = db.Exec(sqlStatement)
        if err != nil {
                fmt.Println("Failed to create table:", sqlStatement, err)
                return
        }
        statement, err := tx.Prepare("insert into SqlDrivers(dbName, pkgLink, testSuite) values(?, ?, ?)")
        if err != nil {
                fmt.Println("Failed to prepare SQL statements:", err)
        }
        defer statement.Close()
        for _, entry := range DbDriverList {
                _, err = statement.Exec(entry.dbName, entry.pkgLink, entry.testSuite)
                if err != nil {
                        fmt.Println("Failed to prepare SQL statements:", err)
                }
        }

        tx.Commit()
}
                fmt.Println("read table")
        rows, err := db.Query("select dbName, pkgLink, testSuite from SqlDrivers")
        if err != nil {
                fmt.Println("Failed to query the database:", err)
      ...
```
I modify two parts, first, I comment os.Remove(dbSourceName)
second, I wrap the create table and insert part into the "if len(os.Args)==2" branch, so that if no args provided, the program runs directly to the read part
2.  I execute the program with one arg, it runs successfully. Then I run the program with no arg, it panic, the error is: 
```
Failed to query the database: no such table: SqlDrivers
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f383c9864f8]

goroutine 1 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/occlum/toolchains/golang/src/database/sql/sql.go:3165 +0x78
database/sql.(*Rows).Close(0x0, 0x0, 0x0)
	/opt/occlum/toolchains/golang/src/database/sql/sql.go:3161 +0x35
panic(0x7f383ccea7a0, 0x7f383cdb3d70)
	/opt/occlum/toolchains/golang/src/runtime/panic.go:965 +0x1b9
database/sql.(*Rows).Next(0x0, 0x7f387c0b2008)
	/opt/occlum/toolchains/golang/src/database/sql/sql.go:2842 +0x32
main.main()
	/root/demos/golang/go_sqlite/simple_demo.go:139 +0x5cd
```
3. I expect the db can store the data of the table, so when the application restarts, it can read the data directly.

# Expected behavior

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW: [e.g. SGX1, SGX2] 
- OS: [e.g. Ubuntu18.04, CentOS8.2]
- Occlum version: [e.g. 0.17.0]

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by guzongmin** [comment]
@james-ray Is the code works out of Occlum enviroment?

**Comment by james-ray** [comment]
No, it is inside Occlum enviroment, 
```
root@f2cf854d6f04:~/demos/golang/go_sqlite# ls
README.md  go_sqlite.yaml  run_go_sqlite_demo.sh  simple_demo.go
root@f2cf854d6f04:~/demos/golang/go_sqlite# vim simple_demo.go
```
It is modified demo code.

**Comment by james-ray** [comment]
```
package main

import (
        "database/sql"
        "fmt"
        _ "github.com/mattn/go-sqlite3"
        "os"
        "time"
)

type GolangDbDriver struct {
        dbName          string
        pkgLink         string
        testSuite       string
}

var DbDriverList = []GolangDbDriver {
        GolangDbDriver {
                dbName: "Apache Ignite/GridGain",
                pkgLink: "https://github.com/amsokol/ignite-go-client",
                testSuite: "Unknown",
        },
        GolangDbDriver {
                dbName: "Amazon AWS Athena",
                pkgLink: "https://github.com/uber/athenadriver",
                testSuite: "Unknown",
        },
        GolangDbDriver {
                dbName: "Google Cloud Spanner",
                pkgLink: "https://github.com/rakyll/go-sql-driver-spanner",
                testSuite: "Unknown",
        },
        GolangDbDriver {
                dbName: "MS SQL Server (pure go)",
                pkgLink: "https://github.com/denisenkom/go-mssqldb",
                testSuite: "Unknown",
        },
        GolangDbDriver {
                dbName: "MySQL",
                pkgLink: "https://github.com/go-sql-driver/mysql/",
                testSuite: "pass the compatibility test suite at https://github.com/bradfitz/go-sql-test",
        },
        GolangDbDriver {
                dbName: "MySQL",
                pkgLink: "https://github.com/siddontang/go-mysql/",
                testSuite: "pass the compatibility test suite but are not currently included in it",
        },
        GolangDbDriver {
                dbName: "Oracle (uses cgo)",
                pkgLink: "https://github.com/mattn/go-oci8",
                testSuite: "Unknown",
        },
        GolangDbDriver {
                dbName: "Postgres (pure Go)",
                pkgLink: "https://github.com/lib/pq",
                testSuite: "pass the compatibility test suite at https://github.com/bradfitz/go-sql-test",
        },
        GolangDbDriver {
                dbName: "Postgres (uses cgo)",
                pkgLink: "https://github.com/jbarham/gopgsqldriver",
                testSuite: "Unknown",
        },
        GolangDbDriver {
                dbName: "Snowflake (pure Go)",
                pkgLink: "https://github.com/snowflakedb/gosnowflake",
                testSuite: "Unknown",
        },
        GolangDbDriver {
                dbName: "SQLite (uses cgo)",
                pkgLink: "https://github.com/mattn/go-sqlite3",
                testSuite: "pass the compatibility test suite at https://github.com/bradfitz/go-sql-test",
        },
        GolangDbDriver {
                dbName: "SQLite (uses cgo)",
                pkgLink: "https://github.com/gwenn/gosqlite",
                testSuite: "Unknown",
        },
        GolangDbDriver {
                dbName: "Apache Hive",
                pkgLink: "https://github.com/sql-machine-learning/gohive",
                testSuite: "Unknown",
        },
}

func main() {
        previousTime := time.Now()
        fmt.Printf("Starting the Golang SQLite demo: at %s\n", previousTime.Format("2006-01-02T15:04:05.999999999Z07:00"))

        dbSourceName := "golang_sql_driver.db"
        //os.Remove(dbSourceName)

        dbDriverName := "sqlite3"
        db, err := sql.Open(dbDriverName, dbSourceName)
        if err != nil {
                fmt.Println("Failed to open the database:", err)
        }
        defer db.Close()

        if err = db.Ping(); err != nil {
                fmt.Println("Failed to establish a connection to the database:", err)
        }

        if len(os.Args)==2{
                fmt.Println("write table")
        tx, err := db.Begin()
        if err != nil {
fmt.Println("Failed to start a database transaction:", err)
        }

        sqlStatement := `
        create table if not exists SqlDrivers (dbName varchar(255), pkgLink varchar(255), testSuite varchar(255));
        delete from SqlDrivers;
        `
        _, err = db.Exec(sqlStatement)
        if err != nil {
                fmt.Println("Failed to create table:", sqlStatement, err)
                return
        }
        statement, err := tx.Prepare("insert into SqlDrivers(dbName, pkgLink, testSuite) values(?, ?, ?)")
        if err != nil {
                fmt.Println("Failed to prepare SQL statements:", err)
        }
        defer statement.Close()
        for _, entry := range DbDriverList {
                _, err = statement.Exec(entry.dbName, entry.pkgLink, entry.testSuite)
                if err != nil {
                        fmt.Println("Failed to prepare SQL statements:", err)
                }
        }

        tx.Commit()
}
                fmt.Println("read table")

        rows, err := db.Query("select dbName, pkgLink, testSuite from SqlDrivers")
        if err != nil {
                fmt.Println("Failed to query the database:", err)
        }
        defer rows.Close()
        for rows.Next() {
                var dbName sql.NullString
                var pkgLink sql.NullString
                var testSuite sql.NullString
                err = rows.Scan(&dbName, &pkgLink, &testSuite)
                if err != nil {
                        fmt.Println("Failed to Scan the query results:", err)
                }
                fmt.Printf("dbName=%v;\n  pkgLink=%v;\n  testSuite=%v\n", dbName.String, pkgLink.String, testSuite.String)
        }
        err = rows.Err()
        if err != nil {
                fmt.Println("Error was encountered during query result iteration:", err)
        }

        _, err = db.Exec("delete from SqlDrivers")
        if err != nil {
                fmt.Println("Failed to delete all records in the database:", err)
        }
         currentTime := time.Now()
        fmt.Printf("Total running time: %f Seconds\n", currentTime.Sub(previousTime).Seconds())

        os.Remove(dbSourceName)
}
```

**Comment by guzongmin** [comment]
When I tried it outside Occlum, the behavior is same as which is inside Occlum. Can you please confirm it works outside of Occlum?

**Comment by james-ray** [comment]
The reason is the code deleltes the db.
 _, err = db.Exec("delete from SqlDrivers")

os.Remove(dbSourceName)


after I comment these two lines, the program reruns well.


By the way, how can we backup db files in this way, because we cannot find the db file.
