### ISSUE TITLE
[BUG] Valid config results in fatal runtime error

### ISSUE THREAD

**Issue by SoulKa** [occlum/occlum#777]
# Describe the bug

I'm receiving a fatal runtime error since I'm providing my own Occlum.json config file. It's actually quite similar to the default config, but I left then env object empty.

# To reproduce
1. Create a new occlum instance
2. Create the Occlum.json as shown below (leave env empty)
3. Occlum build with success (config seems fine)
4. Occlum run fails with a fatal runtime error

# Expected behavior

Receive a precise error where the config is wrong.

# Logs

```
thread '<unnamed>' panicked at 'explicit panic', src/config.rs:18:17
stack backtrace:
   0: sgx_tstd::panicking::begin_panic
   1: spin::once::Once<T>::call_once
   2: <occlum_libos_core_rs::fs::rootfs::ROOT_INODE as core::ops::deref::Deref>::deref::__static_ref_initialize::init_root_inode
   3: spin::once::Once<T>::call_once
   4: occlum_libos_core_rs::fs::fs_view::FsView::lookup_inode
   5: occlum_libos_core_rs::fs::fs_view::FsView::open_file
   6: occlum_libos_core_rs::util::resolv_conf_util::write_resolv_conf
   7: occlum_ecall_init
   8: sgx_occlum_ecall_init
             at /root/occlum/build/internal/src/libos/src/Enclave_t.c:1166
   9: do_ecall
  10: enter_enclave
  11: <unknown>
  12: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum: line 320:   646 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```

# Environment
- HW: SGX2
- OS: Ubuntu18.04 using Occlum Docker
- Occlum version: 0.26.1

# Additional context

This occured only after I provided my own Occlum JSON file. The panic also occures at `src/config.rs:18:17` during the config loading. Unfortunately, I don't get any information if and where my config file might be wrong. My Occlum.json:

```json
{
    "resource_limits": {
        "kernel_space_heap_size": "32MB",
        "kernel_space_stack_size": "1MB",
        "user_space_size": "300MB",
        "max_num_of_threads": 32
    },
    "process": {
        "default_stack_size": "4MB",
        "default_heap_size": "32MB",
        "default_mmap_size": "100MB"
    },
    "entry_points": [
        "/bin"
    ],
    "env": {},
    "metadata": {
        "product_id": 0,
        "version_number": 0,
        "debuggable": true,
        "enable_kss": false,
        "family_id": {
            "high": "0x0",
            "low": "0x0"
        },
        "ext_prod_id": {
            "high": "0x0",
            "low": "0x0"
        }
    },
    "mount": [
        {
            "target": "/",
            "type": "unionfs",
            "options": {
                "layers": [
                    {
                        "target": "/",
                        "type": "sefs",
                        "source": "./build/mount/__ROOT",
                        "options": {
                            "MAC": ""
                        }
                    },
                    {
                        "target": "/",
                        "type": "sefs",
                        "source": "./run/mount/__ROOT"
                    }
                ]
            }
        },
        {
            "target": "/host",
            "type": "hostfs",
            "source": "."
        }
    ]
}
```

**Comment by guzongmin** [comment]
@SoulKa Thank you very much to report issues to us. JSON is not very friendly for dynamic fields, so even if you do not want to fill env, you still need to left them there.
```
  "env": {
    "default": [
    ],
    "untrusted": [
    ]
  },
 ```
  We plan to use YAML as the config language, in hopes that we could solve this issue at that time.

**Comment by SoulKa** [comment]
Thank you for your answer! I also figured out that I need to put these fields back in, I was just confused that the runtime crashes. I'll then close this issue as the matter is resolved for me.
