### ISSUE TITLE
[BUG]Assertion failed in do_futex.rs when running Rust tokio

### ISSUE THREAD

**Issue by AmbitionXiang** [occlum/occlum#869]
# Describe the bug
The bug seems related to async runtime.

# To reproduce
1.
set `rust-toolchain` to `nightly-2021-03-30`
2.
in `Cargo.toml`
```
[package]
name = "rust_app"
version = "1.0.0"
edition = "2018"

[dependencies]
once_cell = "1.3.1"
tokio = { version = "0.2.18", features = ["macros", "parking_lot", "rt-threaded", "rt-util", "signal", "stream", "sync", "time"] }
tokio-util = { version = "0.3.1", features = ["compat"] }
```
3.
in `main.rs`
```
use once_cell::sync::{Lazy, OnceCell};
use tokio::runtime::{Handle, Runtime};

static ENV: OnceCell<Env> = OnceCell::new();
static ASYNC_RT: Lazy<Option<Runtime>> = Lazy::new(Env::build_async_executor);

pub(crate) struct Env {
    v: Vec<u8>,
}

impl Env {
    pub fn get() -> &'static Env {
        ENV.get_or_init(Self::new)
    }

    /// Run a function inside the existing Tokio context.
    pub fn run_in_async_rt<F, R>(func: F) -> R
    where
        F: FnOnce() -> R,
    {
        if let Ok(rt) = Handle::try_current() {
            rt.enter(func)
        } else if let Some(rt) = &*ASYNC_RT {
            rt.enter(func)
        } else {
            unreachable!()
        }
    }

    fn build_async_executor() -> Option<Runtime> {
        if Handle::try_current().is_ok() {
            None
        } else {
            Some(
                tokio::runtime::Builder::new()
                    .enable_all()
                    .threaded_scheduler()
                    .build()
                    .unwrap(),
            )
        }
    }


    fn new() -> Self {
        Env::run_in_async_rt(|| -> Self {
            println!("init env");
            Env {
                v: vec![0u8; 8],
            }
        })
    }
}

fn main() {
    println!("v = {:?}", Env::get().v);
}

``` 
4.  run as in the demo rust_app

# Expected behavior
```
thread '<unnamed>' panicked at 'assertion failed: ret == 0', src/process/do_futex.rs:508:9
stack backtrace:
thread '<unnamed>' panicked at 'assertion failed: ret == 0', src/process/do_futex.rs:508:9
thread '<unnamed>' panicked at 'assertion failed: ret == 0', src/process/do_futex.rs:508:9
thread '<unnamed>' panicked at 'assertion failed: ret == 0', src/process/do_futex.rs:508:9
thread '<unnamed>' panicked at 'assertion failed: ret == 0', src/process/do_futex.rs:508:9
thread '<unnamed>' panicked at 'assertion failed: ret == 0', src/process/do_futex.rs:508:9
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
             at library/core/src/panicking.rs:106
   2: core::panicking::panic
             at library/core/src/panicking.rs:47
   3: occlum_libos_core_rs::process::do_futex::futex_wait_bitset
   4: occlum_libos_core_rs::process::syscalls::do_futex
   5: occlum_libos_core_rs::syscall::dispatch_syscall
   6: occlum_libos_core_rs::syscall::do_syscall
   7: occlum_syscall
   8: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
stack backtrace:
  fatal runtime error:  failed to initiate panic, error 05: 
rust_begin_unwind[ERROR] occlum-pal: Failed to enter the enclave to execute a LibOS thread (host tid = 8137) with error code 0x1006: Unknown SGX error (line 22, file src/ocalls/spawn.c)
/opt/occlum/build/bin/occlum: line 320:  8133 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW: SGX1 
- OS: Ubuntu18.04
- Occlum version: 0.27.0

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by jessehui** [comment]
@AmbitionXiang Please run with this newer image: `docker pull occlum/occlum:0.27.1-ubuntu20.04`. If there is still anything wrong, please inform us. Thanks.

**Comment by AmbitionXiang** [comment]
@jessehui Thank you for your reply. I run with the newer image, and the above issue seems to be solved. However, the output of println in main.rs does not appear. It seems that the program does nothing.

**Comment by jessehui** [comment]
@AmbitionXiang I can run this app in Occlum built with `occlum-cargo` and output exactly the same as running outside the enclave. Did you take a look a look at our rust demo https://github.com/occlum/occlum/tree/master/demos/rust?

**Comment by AmbitionXiang** [comment]
@jessehui Yes, of course. when I run my codes shown above outside the enclave, there are two outputs
```
init env
v = [0, 0, 0, 0, 0, 0, 0, 0]
```
However, when run inside enclaves, there are no outputs at all.

The script I run:
```
set -e

# compile make_rdd
pushd rust_app
occlum-cargo build
popd

# initialize occlum workspace
rm -rf occlum_instance && mkdir occlum_instance && cd occlum_instance

occlum init && rm -rf image
copy_bom -f ../rust-demo.yaml --root image --include-dir /opt/occlum/etc/template

occlum build
occlum run /bin/rust_app
```
And the rust-demo.yaml:
```
includes:
  - base.yaml
targets:
  - target: /bin
    copy:
      - files:
        - ../rust_app/target/x86_64-unknown-linux-musl/debug/rust_app
```

They are the same as in your demo rust_app.

**Comment by jessehui** [comment]
In the script, change `occlum run /bin/rust_app` to `OCCLUM_LOG_LEVEL=trace occlum run /bin/rust_app`. This can give more info about what happens.

**Comment by AmbitionXiang** [comment]
@jessehui Strangely, still nothing outputs...

**Comment by AmbitionXiang** [comment]
Additional info:

I started the container by 
`docker run -it --device /dev/isgx -v /opt/data:/root/data --network=host occlum/occlum:0.27.1-ubuntu20.04`

**Comment by jessehui** [comment]
Oh yes. I just remember there is a bug on SGX 1. You can install the latest Occlum code to fix this. Or you can just modify the Occlum script located at `/opt/occlum/build/bin/occlum` based on https://github.com/occlum/occlum/commit/7772411378fa015eb1a12242f62a1e947e8a3953.

**Comment by AmbitionXiang** [comment]
Thank you very much! It is exactly the reason. Solved.
