### ISSUE TITLE
[RFC]

### ISSUE THREAD

**Issue by pengxj2017** [occlum/occlum#899]
Ubuntu20.04 platform, using the SGX - tree in driver
Hardware platform is Intel Xeon 4314
Use the docker ubuntu20.04, test DCAP remote attestation wrong:

thread 'main' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

docker run command:
mkdir -p /dev/sgx
cd /dev/sgx && ln -sf ../sgx_enclave enclave && ln -sf ../sgx_provision provision
docker run -it --device /dev/sgx/enclave --device /dev/sgx/provision occlum/occlum:latest-ubuntu20.04

**Comment by qzheng527** [comment]
@pengxj2017 Did you set a valid `PCCS_URL` in your container env /etc/sgx_default_qcnl.conf? You have to make sure the container could access the PCCS service as well.

**Comment by pengxj2017** [comment]
> @pengxj2017 Did you set a valid `PCCS_URL` in your container env /etc/sgx_default_qcnl.conf? You have to make sure the container could access the PCCS service as well.

I have already modified the configuration files
/etc/sgx_default_qcnl.conf 

PCCS_URL=https://sgx-dcap-server.cn-hangzhou.aliyuncs.com/sgx/certification/v3/

# To accept insecure HTTPS certificate, set this option to FALSE
USE_SECURE_CERT=TRUE


I switch to another environment
CPU：I5 10400
test EPID remote attesttion Demo is OK
but DCAP demo error:
[get_platform_quote_cert_data ../qe_logic.cpp:347] Error returned from the p_sgx_get_quote_config API. 0xe047
thread 'main' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by qzheng527** [comment]
@pengxj2017 "0xe047" means "SGX_QL_PLATFORM_UNKNOWN, Platform was not found in the cache".
You can try the SGX sample code first to see if the PCCS service can work for your platform.
https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode/QuoteGenerationSample

**Comment by qzheng527** [comment]
> CPU：I5 10400

It is not SGX DCAP avaiable platform.

**Comment by Antone077** [comment]
@qzheng527 [get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe019
thread 'main' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

0xe019 means what？how can i deal with it?

**Comment by Antone077** [comment]
CPU:  Intel® Core™ i5-10505 CPU @ 3.20GHz × 12

**Comment by qzheng527** [comment]
> @qzheng527 [get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe019 thread 'main' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 0xe019 means what？how can i deal with it?

@Antone077 0xe019 means network error. Make sure a valid PCCS_URL in your container env /etc/sgx_default_qcnl.conf.
Also, run `cpuid | grep SGX_LC` in your host to make sure if the SGX/SGX FLC feature is supported on your CPU.
