### ISSUE TITLE
Out of memory error when I run a Rust project

### ISSUE THREAD

**Issue by AmbitionXiang** [occlum/occlum#933]
I meet this error when I run Rust project with occlum, here is the configuration
```
resource_limits.user_space_size = "65536MB" 
resource_limits.kernel_space_heap_size = "16384MB" 
process.default_heap_size = "65536MB" 
process.default_mmap_size = "16384MB" 
resource_limits.max_num_of_threads = 64 
```
And the error
```
tcs_num 64, tcs_max_num 64, tcs_min_pool 1
The required memory is 85971787776B.
The required memory is 0x1404516000, 83956824 KB.
Succeed.
failed to boot up LibOS: ENOMEM (#12, Out of memory): failed to create process VM [line = 17, file = src/process/do_spawn/init_vm.rs]
    Caused by ENOMEM (#12, Out of memory): can't allocate free chunks [line = 66, file = src/vm/vm_manager.rs]
[ERROR] occlum-pal: occlum_ecall_new_process returns ENOMEM (line 194, file src/pal_api.c)
[ERROR] occlum-pal: Failed to run the init process: ENOMEM (line 140, file src/pal_api.c)
thread '<unnamed>' panicked at 'assertion failed: USER_SPACE_VM_MANAGER.verified_clean_when_exit()', src/vm/user_space_vm.rs:50:5
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
             at library/core/src/panicking.rs:106
   2: core::panicking::panic
             at library/core/src/panicking.rs:47
   3: occlum_libos_core_rs::vm::user_space_vm::free_user_space::__dtor_export::free_user_space
   4: uninit_global_object
   5: do_uninit_enclave
   6: enter_enclave
   7: <unknown>
   8: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
^C/opt/occlum/build/bin/occlum: line 337:   925 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```

My machine:
Intel(R) Xeon(R) Gold 5317 CPU @ 3.00GHz and 377GB memory.
Occlum version 0.27.0

**Comment by jessehui** [comment]
Thanks for using Occlum. Please be noted that the process heap and stack are allocated from the `resource_limits.user_space_size`. 

I am not sure why you use the number for this configuration, but a simple way is to decrease the size of process heap and stack size. And for memory resource configuration, please take a look at this [doc](https://github.com/occlum/occlum/blob/master/docs/resource_config_guide.md).

**Comment by AmbitionXiang** [comment]
Thanks for your reply! It works. However, I meet another issue, same as https://github.com/occlum/occlum/issues/364. Now I'm checking whether it is about fsgsbase.

**Comment by AmbitionXiang** [comment]
I open another issue https://github.com/occlum/occlum/issues/937 regarding the new problem. Closing the current issue. Thanks.
